### ISSUE TITLE
Plugin doesn't work with test or library modules.

### ISSUE THREAD

**Issue by jchudev** [Karumi/Shot#100]
I am attempting to build a test module using the `com.android.test` gradle plugin but this doesn't seem to be compatible with `4.1.1`. Using versions `3.1.0` allows me to sync successfully. This is also the same case with `com.android.library`.

### Expected behaviour
Gradle syncs successfully.

### Actual behaviour
```
> Extension of type 'AppExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, DefaultArtifactPublicationSet, ReportingExtension, SourceSetContainer, JavaPluginExtension, JavaInstallationRegistry, NamedDomainObjectContainer<BaseVariantOutput>, TestExtension, KotlinAndroidProjectExtension, KotlinTestsRegistry, AndroidExtensionsExtension, ShotExtension]
```

### Steps to reproduce
1. I added the following to the test module's `build.gradle` from the instructions.
```  
buildscript {
    // ...
    dependencies {
      // ...
      classpath 'com.karumi:shot:4.1.1'
    }
}
apply plugin: 'shot'
```
2. Run gradle sync

### Version of the library
4.1.1

**Comment by fmontesino** [comment]
I solved this by installing shot as usual, then in my library module:
```
dependencies {
   // ...
    api 'com.karumi:shot-android:4.1.1'
}
```
I hope it helps!

**Comment by pedrovgs** [comment]
Hi @jchudev you are absolutely right. Version 4.X improved flavors support, however by mistake we broke libraries support :( This is going to be my next fix. Could you please confirm if @fmontesino 's workaround works?

**Comment by pedrovgs** [comment]
Hi @fmontesino I've just merged a PR fixing the support for android libs. This was supported in previous versions just for free because we were not using the official gradle plugin in order to link Shot's tasks with android testing tasks. I'm releasing a new version with the fix right now. Please, check if it's working for you and feel free to reopen this issue if it doesn't work.

**Comment by jchudev** [comment]
@fmontesino Thanks for the suggestion. That didn't seem to work due to it failing on trying to find `AppExtension` when running a gradle sync.

@pedrovgs I tried `4.2.0` and it syncs successfully on both test and library modules! I ran a test on the library module and it worked just fine. Thanks for all the help everybody!
