### ISSUE TITLE
Shot plugin significantly increases configuration time when applied

### ISSUE THREAD

**Issue by runningcode** [Karumi/Shot#113]
Shot plugin significantly increases configuration time of builds when it is applied.
In larger projects, we've seen this plugin add 60 seconds to the configuration time of the build.
The plugin adds a `beforeResolve` hook to every Configuration in the entire multi-project build. This is terrible, since if you have N projects, you’ll be adding N listeners, and each listener will apply to every configuration that is resolved.
When any arbitrary configuration is resolved in the entire build, N beforeResolve hooks will fire.

https://github.com/Karumi/Shot/blob/master/shot/src/main/scala/com/karumi/shot/ShotPlugin.scala#L180

There are 2 options to improve this:
1. Remove the hooks and developers must explicitly add the dependency.
2. Always add the dependency like below. Developers can override the version by adding it explicitly if needed.
```
configurations.add 'shotLibrary'
configurations['androidTestImplementation'].extendsFrom 'shotLibrary'
configurations['shotLibrary'].defaultDependencies 'com.karumi:shot-android:1.0'
```

Thanks to @rallat and @bigdaz for helping discover this.

**Comment by pedrovgs** [comment]
Hi @runningcode thanks for reporting. We should definitively improve this part of the gradle plugin. I'm going to check if there is any other approach we can use to be able to respect the original library behavior and keep it as fast as possible. Meanwhile, if you find a solution and you'd like to contribute, feel free to send any PR 😃

**Comment by runningcode** [comment]
From my understanding the second approach would respect the current behavior and keep it as fast as possible.

**Comment by pedrovgs** [comment]
I think you are right @runningcode but I need to test if works properly in the second scenario. If you want to send a PR with that approach that would be awesome 😃I can release a new version as soon as we have the fix 😃 If you don't have time, I totally understand it, we will have to wait until I can implement it by myself or we find any other collaborator.

**Comment by pedrovgs** [comment]
Hi @runningcode I've released a new version with the build time improvement. As soon as the version 4.3.0 is indexed by Maven Central you'll be able to use it 😃

**Comment by rallat** [comment]
Thanks!

**Comment by pedrovgs** [comment]
Hey @rallat @runningcode did you check if the fix is working for you?
