### ISSUE TITLE
Add in configurability of clearing app data state between tests

### ISSUE THREAD

**Issue by justin-segler** [Karumi/Shot#122]
### Expected behaviour

(Note: After some investigation and trial/error, I have not found that this has yet been implemented. However, if it already is a feature of Shot, I would love to be informed on this. In this cast, please just close this issue.)

One very helpful feature of Shot would be the ability for `ShotTestRunner` to take in a `clearPackageData` argument in `build.gradle` which clears the app data between each test being run.

### Actual behaviour

I have attempted to add in this line into the `defaultConfig` section of the `build.gradle` beneath the setting of the `testInstrumentationRunner`; however, it is not producing the intended results:

`testInstrumentationRunnerArguments clearPackageData: 'true'`

Implementing the ability for this argument to be passed to the test runner upon its initialization would give greater control to devs in managing the state of their app while running Shot tests.

### Version of the library

4.3.0

**Comment by pedrovgs** [comment]
Hey @justin-segler thanks for opening the issue. I've been thinking about it and I think this is out of the library scope right now. However, you can implement it by yourself creating class extending from ``ShotTestRunner``.
