### ISSUE TITLE
Report does not contain custom name when custom name is defined through `name` parameter of `captureScreenshot`

### ISSUE THREAD

**Issue by malvinstn** [Karumi/Shot#126]
### Expected behaviour

The generated report should use the custom name defined using `name` parameter as the test name.

### Actual behaviour

The generated report uses the actual test method name as the test name. Even though the screenshots are named correctly.
![Screen Shot 2020-07-03 at 11 26 18 AM](https://user-images.githubusercontent.com/2493177/86425537-6a679d80-bd20-11ea-95ff-06b7f4f3253d.png)

### Steps to reproduce
- Call `createScreenshot` with a custom name:
```kotlin
    @Test
    fun testActivity() {
        val activity = launchActivity()
        compareScreenshot(activity, name = "aCustomName")
    }
```
- Run `./gradlew executeScreenshotTests -Precord`
- Change the UI to make the comparison fail
- Run `./gradlew executeScreenshotTests`
- Check the generated report in `build/reports/shot/verification/index.html`

### Version of the library

`com.karumi:shot:4.3.0`

**Comment by malvinstn** [comment]
Seems like the generated `metadata.xml` does not have the correct `test-name` element. This can probably be fixed easily by calling `setTestName` of the screenshot here: https://github.com/Karumi/Shot/blob/master/shot-android/src/main/java/com/karumi/shot/ScreenshotTest.kt#L131
Let me know if you want me to create a PR for this

**Comment by pedrovgs** [comment]
Hi @malvinstn thank you so much for the detailed issue. It could be great if you want to contribute 😃 I'll personally review your changes and release a new version with the fix 😃

**Comment by malvinstn** [comment]
I tried to dig at the implementation deeper, and it seems like Facebook lib that shot is using does not expose the `setTestName` method on the `RecordBuilder` interface. I'll try to bring this issue to Facebook's lib instead.

**Comment by pedrovgs** [comment]
Sorry for the late response @malvinstn I broke one arm and I've been out for some time. As you mentioned, there is nothing we can do until https://github.com/facebook/screenshot-tests-for-android/issues/255 is fixed. I'm closing the issue in the meantime.
