### ISSUE TITLE
Fetch screenshots from only one emulator with multiple emulators running

### ISSUE THREAD

**Issue by tobiasKaminsky** [Karumi/Shot#130]
- have two emulators run:
» adb devices
List of devices attached
emulator-5554   device
emulator-5556   device

- use ANDROID_SERIAL to specify one emulator
ANDROID_SERIAL=emulator-5556 ./gradlew gplayDebugExecuteScreenshotTests

- see that tests run only on specific emulator :+1: 
-  but downloading fails with:
> Task :gplayDebugDownloadScreenshots FAILED
⬇️  Pulling screenshots from your connected devices!

**Comment by pedrovgs** [comment]
Hi @tobiasKaminsky thanks for reporting the issue. The emulator does not take into account the ANDROID_SERIAL parameter you mentioned and is trying to download the screenshots from all the connected devices. You can see [here](https://github.com/Karumi/Shot/blob/master/core/src/main/scala/com/karumi/shot/Shot.scala#L142) how the parameter you mentioned is ignored. As a workaround, I'd recommend killing one of the emulators before executing your task ``gplayDebugExecuteScreenshotTests``.


If you don't mind, I'm renaming this issue so we can better track the state of the project. Right now I have other tasks to do related to shot, but if I have time I'll try to fix this bug soon. If you have time and you'd like to contribute, feel free to send a PR with the fix. Thank you in advance.

**Comment by pedrovgs** [comment]
There is another workaround I didn't mention. You can configure Shot to run tests in all the configured devices using composer. This will use sharding and will speed up your tests' execution. You can find more information [in the repository documentation](https://github.com/Karumi/Shot#executing-tests-in-multiple-devices)

**Comment by pedrovgs** [comment]
I have a WIP branch with some code I had no time to manually test. I had only time for the automated tests ``respect-android-serial-env-var`` I'll continue working on this whenever I have time. Meanwhile, if someone would like to finish the branch I'll be happy to help 😃

**Comment by anhduy5689h** [comment]
> in the repository documentation
I have the same issue with ANDROID_SERIAL, and I'm also researching it.
About the Composer, it's too complicated, could you make a simple project (example) with some descriptions of how to config it? Thanks!

**Comment by pedrovgs** [comment]
I'm about to send a PR with the ANDOIRD_SERIAL fix. About Composer, you have a sample project configured and their documentation.
