### ISSUE TITLE
Have any solution no need to uninstall the application after executing the report of 1 @Test done?

### ISSUE THREAD

**Issue by anhduy5689h** [Karumi/Shot#137]
### Expected behaviour
Don't want to uninstall the application when a @Test finish.

### Actual behaviour
The application is uninstalled when a @Test finish.

### Steps to reproduce
Execute report for a class with 2 @Test.

### Version of the library
4.4.0

**Comment by pedrovgs** [comment]
We can not handle when the app is uninstalled. There is nothing we can do to change the way the instrumentation tests work.
