### ISSUE TITLE
IDE not picking up shot-android sources

### ISSUE THREAD

**Issue by drewhamilton** [Karumi/Shot#139]
### Expected behaviour
Clicking into ScreenshotTest function calls opens ScreenshotTest.kt

### Actual behaviour
Clicking into ScreenshotTest function calls opens ScreenshotTest.class, which must be decompiled into Java to see any useful code

### Steps to reproduce
Apply Shot to a project

### Version of the library
4.4.0

I see that the sources JARs are on Maven Central, so I assume they're supposed to be visible. I suppose it has something to do with the sources coming from the Gradle plugin rather than a "normal" dependency?

This made it a bit difficult to start debugging #135.

**Comment by pedrovgs** [comment]
You are absolutely right. There is something wrong with the artifacts deploy configuration which is not uploading the project sources. I'm going to start working on a different feature now so I won't have time to fix this soon. However, if any other contributor would like to participate I'll personally review the fix.
