### ISSUE TITLE
Generate a report at specified directory

### ISSUE THREAD

**Issue by stephen1706** [Karumi/Shot#142]
### Expected behaviour
Able to generate the report at a certain directly

### Actual behaviour
Currently the test always generated at `./build/reports/shot/record/index.html`

### Steps to reproduce
Run  `./gradlew debugExecuteScreenshotTests -Precord`

### Version of the library
4.4.0

Hi, is there any way to generate the report outside the default build folder?
Thank you

**Comment by pedrovgs** [comment]
Nope, it is not.

**Comment by pedrovgs** [comment]
Closing because it is duplicated by #86
