### ISSUE TITLE
ShotTestRunner crashes in `finish` on Android 29+

### ISSUE THREAD

**Issue by drewhamilton** [Karumi/Shot#161]
Unlike [previous issues](https://github.com/Karumi/Shot/issues/120) on API 29+, which affect only the `executeScreenshotTests` task, this affects instrumented tests in general when ShotTestRunner is used.

### Expected behaviour
Instrumented test suites pass on Android 29+ when run with ShotTestRunner.

### Actual behaviour
After all the tests pass, the test process crashes. The stack trace points to the new Compose support in `ShotTestRunner.finish`:
```
2020-10-14 14:48:34.422 26527-26559/my.package.test E/AndroidRuntime: FATAL EXCEPTION: Instr: com.karumi.shot.ShotTestRunner
    Process: my.package.test, PID: 26527
    java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
        at java.io.File.createNewFile(File.java:1008)
        at com.karumi.shot.compose.ScreenshotSaver.createFileIfNotExists(ScreenshotSaver.kt:69)
        at com.karumi.shot.compose.ScreenshotSaver.saveSerializedMetadata(ScreenshotSaver.kt:42)
        at com.karumi.shot.compose.ScreenshotSaver.saveMetadata(ScreenshotSaver.kt:30)
        at com.karumi.shot.compose.ComposeScreenshot.saveMetadata(ComposeScreenshot.kt:20)
        at com.karumi.shot.compose.ComposeScreenshotRunner$Companion.onDestroy(ComposeScreenshotRunner.kt:17)
        at com.karumi.shot.ShotTestRunner.finish(ShotTestRunner.kt:18)
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:404)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
```

### Steps to reproduce
1. Create an Android project that uses ShotTestRunner. (My project does not use Compose at all and is not currently calling `compareScreenshot` at all.)
2. Launch an emulator on Android API 29
3. `./gradlew clean connectedCheck`

If all the tests pass, this command fails due to "process crashed", and the logcat shows the stacktrace from above.

### Version of the library
5.1.2, 5.2.0

**Comment by pedrovgs** [comment]
Hi @drewhamilton thanks for reporting. You are right, there is a bug. Could you please send a PR with the fix. I'm a little bit busy right now :(

**Comment by drewhamilton** [comment]
I can try. I need to understand what's happening better in order to figure out what to do.

ShotTestRunner wants to save a metadata file to the device whenever it finishes. This metadata file contains information about each time `compareScreenshot` was called during the test suite. This is so the `executeScreenshotTests` task can read the same metadata later on, during `verifyScreenshots`.

The non-Compose `ScreenshotRunner` doesn't need any such metadata file—it just pulls the screenshots directly from the known directory. Why does the Compose one need this metadata file?

**Comment by pedrovgs** [comment]
The metadata file is needed to know how many tests were executed. The fix should be as simple as avoid writing the file if the metadata is empty. Checking [here](https://github.com/Karumi/Shot/blob/master/shot-android/src/main/java/com/karumi/shot/compose/ComposeScreenshot.kt#L20) if session is empty should be enough.

**Comment by drewhamilton** [comment]
If I'm reading it right, that will fix this issue for non-Compose users, but Compose users will still be unable to run `connectedCheck` on Android 29+. Because the Compose-friendly `compareScreenshot` will add to the metadata even if only `connectedCheck` is run, right?

If that's correct, another option could be to `if` check the OS version before the file write. That way `connectedCheck` would pass no matter what, and only `executeScreenshotTests` would fail, for both Compose and non-Compose users.

Which do you prefer?

**Comment by pedrovgs** [comment]
You are right @drewhamilton. Right now we can't execute compareScreenshot on Android 29+. I think we should apply both strategies. Do not write metadata if it is empty and also do not write it if it is not empty but the OS si 29+. That should get Shot working for both scenarios.

**Comment by pedrovgs** [comment]
Fixed by @drewhamilton ! Thanks 😃
