### ISSUE TITLE
Download fails for custom buildType with applicationIdSuffix but without product flavour

### ISSUE THREAD

**Issue by dabele91** [Karumi/Shot#162]
### Expected behaviour
The download task uses the correct folder

### Actual behaviour
The download task tries to download the screenshots from a wrong folder.
The screenshots are e.g. in the `/sdcard/screenshots/com.example.app.dummy/` folder, but the download task tries to download from the `/sdcard/screenshots/com.example.app.dummy.dummy/` folder

### Steps to reproduce
1. Create Project with a new buildType named `dummy` and an applicationIdSuffix with the value `.dummy` and don't add a product flavour (you also have to set testBuildType = "dummy" for that buildType)
2. Execute the snapshot tests with your build type e.g.: `./gradlew dummyExecuteScreenshotTests`
3. The snapshot tests are running, but the download task fails with the following exception:

```
Shot ADB warning: We could not pull screenshots from folder: /sdcard/screenshots/com.example.app.dummy.dummy.test/screenshots-default/
Shot ADB warning: We could not pull screenshots from folder: /sdcard/screenshots/com.example.app.dummy.dummy.test/screenshots-compose-default/
Shot ADB warning: rm: /sdcard/screenshots/com.example.app.dummy.dummy.test/screenshots-default/: No such file or directory
Shot ADB warning: rm: /sdcard/screenshots/com.example.app.dummy.dummy.test/screenshots-compose-default/: No such file or directory
```

### Version of the library
Shot: 5.2.0

Android Gradle Plugin: 4.1.0

**Comment by Cotel** [comment]
Is there any version to which we can downgrade and make it work?

**Comment by dabele91** [comment]
I don't think so. 
It's the only reason why we aren't able to upgrade to the newest android gradle plugin, so we still use an old android gradle plugin version.

**Comment by pedrovgs** [comment]
@dabele91 @Cotel  I'm afraid this is an issue related to the Android Gradle plugin which is constantly changing :( There is even a warning if you use one of the latest versions. I fixed the same bug for the flavor configuration, not for the build type. Let's see if I can find some time to fix this issue. Thanks for reporting.

**Comment by Cotel** [comment]
I can try to solve this if you guide me a little bit @pedrovgs

**Comment by pedrovgs** [comment]
I'm going to be working on Shot today. If I can't fix it by the end of the day I'll write an update here and I'll let you know how you can fix it. I really appreciate your help @Cotel 😃

**Comment by pedrovgs** [comment]
It's done @Cotel it should be released soon.

**Comment by Cotel** [comment]
Amazing, thank you 😍

**Comment by dabele91** [comment]
Works, Thanks :)
