### ISSUE TITLE
[not-a-bug] screenshotbot.io

### ISSUE THREAD

**Issue by tdrhq** [Karumi/Shot#163]
Hi @pedrovgs  and gang,

I was the original author of screenshot-tests-for-android, though I don't work at Facebook anymore.

I recently built https://screenshotbot.io, it's a service that runs screenshot tests the way we ran it at Facebook (which I also built, and eventually scaled across all of our Android and iOS projects): run it on master every now and then, upload to the "cloud", if things changes then send out a task cc-ing appropriate people. Basically no recording and verifying, we assume that most screenshot changes are intentional and not regressions. It's much more nicer flow and scales up better with lots of repositories and shared code. (Here's an example github issue that the flow created: https://screenshotbot.io/report/3)

Now because you guys maintain Shot, I'm guessing you use screenshot testing quite a bit at Karumi. I'd be happy to set up screenshotbot.io for you guys, I don't intend to charge you guys since you'd literally be my first external user.

Let me know what you think. You can reach back to me at arnold@tdrhq.com if you want to take this conversation offline.

Cheers!
Arnold

**Comment by pedrovgs** [comment]
Hi @tdrhq we use GitHub issues for error tracking and not for regular communication between our contributors. Please if you'd like to contact us send us an email. I'm afraid I have to close this issue.
