### ISSUE TITLE
Allow storing bitmaps from any source.

### ISSUE THREAD

**Issue by Laimiux** [Karumi/Shot#167]
### What
Currently, to support `Compose`, Shot provides a custom runner that captures allows to take those screenshots and the plugin picks them up. It would be useful to have a more generic approach such as
```kotlin
object ShotRunner {
  fun saveScreenshot(bitmap: Bitmap, name: String?)
}
```
One of the use-cases is to allow capturing screenshots using https://github.com/jraska/Falcon instead of the Facebook library. The improvement here is that it captures all windows allowing dialogs and popup windows to be captured as well.

**Comment by Laimiux** [comment]
Looking at this more, it looks like there are types of format for test results: compose json and facebook XML based formats. Maybe there should be one format that Shot works with and those two are mapped to that format?

**Comment by pedrovgs** [comment]
You are absolutely right @Laimiux! It could be nice. I'm providing support right. now 😃

**Comment by Laimiux** [comment]
> You are absolutely right @Laimiux! It could be nice. I'm providing support right. now 😃

Looks great, thanks for doing it 💯

**Comment by pedrovgs** [comment]
It has been already released btw. I forgot to mention it 😃
