### ISSUE TITLE
Cannot pull screenshots from phone

### ISSUE THREAD

**Issue by tuliopereirazup** [Karumi/Shot#172]
### Expected behaviour
Run `./gradlew executeScreenshotTests -Precord` and fetch screenshots from phone.

### Actual behaviour
I'm trying to create the snapshots but Shot cannot pull screenshots from phone.

Here is the log from Gradle:
```gradle
> Task :app:debugDownloadScreenshots
⬇️  Pulling screenshots from your connected devices!
Shot ADB warning: We could not pull screenshots from folder: /sdcard/screenshots/br.com.zup.shottestapp.test/screenshots-default/
Shot ADB warning: We could not pull screenshots from folder: /sdcard/screenshots/br.com.zup.shottestapp.test/screenshots-compose-default/
Shot ADB warning: rm: /sdcard/screenshots/br.com.zup.shottestapp.test/screenshots-default/: No such file or directory
Shot ADB warning: rm: /sdcard/screenshots/br.com.zup.shottestapp.test/screenshots-compose-default/: No such file or directory

> Task :app:debugExecuteScreenshotTests FAILED
💾  Saving screenshots.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:debugExecuteScreenshotTests'.
> java.lang.NullPointerException (no error message)
```

### Steps to reproduce
Just create new project, follow the steps on README.md and run the command `./gradlew executeScreenshotTests -Precord` and the error will occur.

### Version of the library
5.3.0

**Comment by tuliopereirazup** [comment]
I'm not sure why but if I put this dependency it works fine: `implementation 'com.facebook.testing.screenshot:core:0.13.0'`.

**Comment by ditn** [comment]
I'm also seeing this even on extremely simple sample projects. I expect it's something to do with targeting API 30.

**Comment by michal-konkel** [comment]
Same here.

**Comment by hamorillo** [comment]
I think it's a problem with the API that you are targeting or the device API. There are some issues with the new Storage System on API 29 and API 30. You could find more detailed info in PR #168.

Take a look at [Shot on API 29](https://github.com/Karumi/Shot#using-shot-on-api-29). If you are using compose you should wait to the next release, but if your aren't using compose in your app you could try with the lastest release.

**Comment by pedrovgs** [comment]
@tuliopereirazup can you confirm if it works on an emulator with API 28?

**Comment by ditn** [comment]
I saw the related PR, and I spent approximately 4 hours attempting to get Shot running on all sorts of combinations of target API, emulator API and shot version. Couldn't get it to work at any point.

**Comment by pedrovgs** [comment]
@ditn if you upload a project reproducing the issue I'll personally take a look at what's going on.

**Comment by tuliopereirazup** [comment]
I'm tried a bunch of things, like executing the project on old emulators (API, 23, 26, 27, 28) and change compileSdk and targetSdk to older ones too.

**Comment by tuliopereirazup** [comment]
@pedrovgs, here is the project to reproduce the bug.

https://github.com/tuliopereirazup/shot-sample-issue

**Comment by pedrovgs** [comment]
@tuliopereirazup I've found the issue. You have to configure the ``android:sharedUserId="br.com.zup.shottestapp.uid"`` in your ``app/AndroidManifest.xml`` file. You did it in the test manifest but not in the app manifest. Please, try it out and let me know if we can close this issue.

**Comment by tuliopereirazup** [comment]
Ohh sorry, I did this typo before uploading the repo to GitHub trying to rename the project package name.
But this is not the cause of the error, I fixed this typo and the error continues.

**Comment by pedrovgs** [comment]
It is not a typo error. You need to add the ``android:sharedUserId`` to two configuration files. The ``androidTest`` manifest and also the ``app`` manifest. The value is not relevant as soon as it is the same in both files.

**Comment by tuliopereirazup** [comment]
Hmmm... now I got it hehe.

Thanks, that missing configuration worked! 😃

**Comment by pedrovgs** [comment]
Happy to see you got it working @tuliopereirazup !! Happy testing 😃
