### ISSUE TITLE
Output only failing screenshots

### ISSUE THREAD

**Issue by tobiasKaminsky** [Karumi/Shot#175]
We heavily use your app and have many many screenshot tests.
If now e.g. 1 or 2 are failing ouf of 100, then CI needs to upload all tests.
In this case it would be better to just show a quick summary, like you already do on verification and then only print those failing tests.

**Comment by pedrovgs** [comment]
@tobiasKaminsky could you implement this feature as a configurable parameter in the plugin extension?

**Comment by tobiasKaminsky** [comment]
I tried it and followed https://github.com/Karumi/Shot#steps-to-develop-a-feature-or-fix-a-bug
But after ./gradlew uploadArchives my AndroidStudio does not pick it up.
I see in $shot/repo/… shot-5.4.1-20201119.145130-4.jar

But when adding this to my build.gradle in my Android project, it does not pick it.
I tried to understand how to add the repo as a local maven repo, but I failed…

Opening shot-android and trying to gradle sync fails with:
Task 'wrapper' not found in project ':shot-android'.

Do you have an idea what is wrong? :-)

**Comment by pedrovgs** [comment]
@tobiasKaminsky shot-consumer-x folders are designed to be open with Android Studio as a single project and not as gradle modules. You'll need to import them as if you were importing any other app. Before being able to run the consumer tests you'll need to run ``./gradlew uploadArchives`` from the main project. Whenever you change the plugin code you'll have to execute ``./gradlelw uploadArchives`` again. Keep in mind shot android is a module part of the main project. My recommendation is to open the root folder of the repository using IntelliJ and the consumers using android X as I mentioned before. Let me know if you need anything else.

**Comment by tobiasKaminsky** [comment]
@pedrovgs I finally found the time. Looking forward to your feedback :-)

**Comment by pedrovgs** [comment]
Great! I'm going to take a look.

**Comment by tobiasKaminsky** [comment]
I just noticed that CI complains about code syntax. As I cannot see what is wrong, only which file, and I am not 100% sure about desired code syntax, I hope it is okay, to leave this to you? 🤞

**Comment by pedrovgs** [comment]
Don't worry. You can use a command to automatically format the code for you 😃
