### ISSUE TITLE
executeScreenShots only shows partial results in the report

### ISSUE THREAD

**Issue by proto-mvp** [Karumi/Shot#177]
### Expected behaviour
I have updated to latest version of the plugin, 5.4.0, and when running the <Flavor><Build>executeScreenshots,e.g. **myAppDebugExecuteScreenShots** suite of tests for a package, I am expecting to see a report with all the tests and their results

I didn't have any issues on that on previous version.

### Actual behaviour
I am running the <Flavor><Build>executeScreenshots,e.g. **myAppDebugExecuteScreenShots** option to a given package, or class name, with the right option each time, and in the end of the tests the report shows me only the result of one test out of either 200, if it is the root package, or one even out of 10 let's say for a given class.

### Steps to reproduce
<Flavor><Build>executeScreenshots -Pandroid.testInstrumentationRunnerArguments.package=com.myapp.tests.integration.screenshot

or
<Flavor><Build>executeScreenshots -Pandroid.testInstrumentationRunnerArguments.class=com.myapp.tests.integration.screenshot.TestOfSomeEntity

### Version of the library
Latest 5.4.0

**Comment by pedrovgs** [comment]
@proto-mvp I've tested the latest two versions and it is working as expected. Could you provide more information or a reproducible example? Thank you in advance!

**Comment by proto-mvp** [comment]
Hi @pedrovgs 
It is no longer an issue. It was due to the test runner not configured correct.
Will close this issue.
Thank you!
