### ISSUE TITLE
Inconsistent screenshots between two exact Pixel 2 API 27 devices 

### ISSUE THREAD

**Issue by sanginovs** [Karumi/Shot#179]
Hi there, 

I take baseline screenshots locally using Pixel 2 API 27 emulator. Then, I compare local screenshots against generated Test Lab screenshots. I am using the same emulator device model + API level in test lab.
However, the screenshot comparison fails because the original screenshot dimension: 1080x1794 while the firebase test lab screenshot is 1080x1788 even though they are running in the same exact device model + API level.
Any idea why they are generating screenshots of different sizes?

### Expected behaviour
Should generate same size screenshot

### Actual behaviour
Generating images of different sizes that's why verification fails. 
<img width="1078" alt="Screen Shot 2020-11-06 at 10 08 06 AM" src="https://user-images.githubusercontent.com/16856287/101792085-25a71600-3ab9-11eb-9687-6ffb09254695.png">

### Steps to reproduce
Run ./gradlew screenshot task to generate baseline screenshot locally. 
Run screenshot task in Firebase test lab. 
Verify the two. 

### Version of the library
Latest. 

I also made a post on Firebase Slack channel. Here's the thread:

![Screen Shot 2020-12-10 at 7 30 09 AM](https://user-images.githubusercontent.com/16856287/101792424-89c9da00-3ab9-11eb-97b1-c8c45dac1ca1.png)

**Comment by pedrovgs** [comment]
Hi @sanginovs are you Jetpack Compose for your UI? If the device is the same I can ensure the screenshot will be the same. Could you please get the hardware details of the device you use in firebase test lab? If you are using compose ensure you run your baseline screenshots with the same Shot version you use to verify your tests. Between some shot versions the code compose provides to get a bitmap from a component has changed the way it works and can generate some differences between versions. Last question. Do your tests pass when you run the verification test in your emulator?

**Comment by sanginovs** [comment]
@pedrovgs i am not using Jetpack Compose. I looked up Firebase test lab device specs:
![Screen Shot 2020-12-15 at 7 58 32 AM](https://user-images.githubusercontent.com/16856287/102239081-54533100-3eab-11eb-8891-6e1147938c82.png)

Here's my local emulator Pixel 2 specs:
<img width="1326" alt="Screen Shot 2020-12-15 at 7 58 46 AM" src="https://user-images.githubusercontent.com/16856287/102239115-5cab6c00-3eab-11eb-8f97-aa9bebe5792c.png">


Looks like the difference is screen size. As you can see from the screenshot, Firebase pixel 2 resolution is  1920 x 1080 while my emulator is 1080 x 1920. I will try to find a Firebase device that will exactly match my local emulator. Thanks for your time @pedrovgs

**Comment by sanginovs** [comment]
@pedrovgs here's an update. i just tested it again. 
1. I manually downloaded generated screenshots from firebase and verified it locally by running this cmd: `./gradlew executeScreenshotTests -PrunInstrumentation=false`. It's being verified and i dont run into different image size error. 

2. However, when running the same cmd from CirceCI and verifying against the same baseline images, i am getting `The size of the screenshot taken has changed for test ..` error.

Any idea?

**Comment by sanginovs** [comment]
@pedrovgs i was able to resolve this issue. Looks like firebase test lab has different versions of Pixel2 device. i had to provide extra information: `model=walleye,version=27,locale=en_US,orientation=portrait`
That's what was causing this issue. thanks for your help.

**Comment by pedrovgs** [comment]
Thanks for the extra info @sanginovs 😃 I'm happy to see you got it working.
