### ISSUE TITLE
Problems with gradle version 3.0.0-beta or upper.

### ISSUE THREAD

**Issue by flipper83** [Karumi/Shot#18]
### Expected behaviour
execute the gradle task

### Actual behaviour

when running the gradle task throw this error:

> Configure project :uripatch
> Configuration 'androidTestCompile' in project ':uripatch' is deprecated. Use 'androidTestImplementation' instead.
> Configuration 'compile' in project ':uripatch' is deprecated. Use 'implementation' instead.

and after that this cause a Multidex exception:

> Dex: Error converting bytecode to dex:
> Cause: com.android.dex.DexException: Multiple dex files define Lcom/android/dx/dex/file/IdItem;
>     UNEXPECTED TOP-LEVEL EXCEPTION:
>     com.android.dex.DexException: Multiple dex files define Lcom/android/dx/dex/file/IdItem;

### Steps to reproduce
1) create a kotlin proyect with gradle build version 3.0.0-beta-1 or upper.
2) add shot plugin
3) try to record the tests with ./gradlew executeScreenshotTests -Precord
4) Throw the exception
### Version of the library

version 0.1.2

**Comment by pedrovgs** [comment]
@flipper83 is Gradle 3.0.0 still in beta?

**Comment by flipper83** [comment]
Sorry its android plugin beta 3, last one is beta 4, and cotains gradle
version 4.1-rc-1.

And this change is for gradle 4. This version its that google recommend for
kotlin development

**Comment by pedrovgs** [comment]
Fixed by @flipper83 and released in Shot 0.2.0 😃
