### ISSUE TITLE
java.nio.file.FileAlreadyExistsException

### ISSUE THREAD

**Issue by anhduy5689h** [Karumi/Shot#180]
I ran ... executeScreenshotTests -Precord .... The Task :app:connectedMockAppDebugAndroidTest show SUCCESS (green) then
Pulling screenshots from your connected devices!
Task :app:mockAppDebugDownloadScreenshots in debugsettings Finished

> Task :app:mockAppDebugDownloadScreenshots FAILED
:app:mockAppDebugDownloadScreenshots (Thread[Execution worker for ':',5,main]) completed. Took 2.329 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mockAppDebugDownloadScreenshots'.
> java.nio.file.FileAlreadyExistsException: /Users/myAccount/Folder/ProjectFolder/app/screenshots/mockApp/debug/screenshots-default/home_step1.png

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 56s
398 actionable tasks: 9 executed, 389 up-to-date

### Version 4.3.0 and 4.4.0

I executed success many times, but this week it's always failed. I didn't update anything. I ran Clean Project, Invalidate Cache, restart the machine, uninstall the app and restart my phone, delete screenshots folder, delete all build folder in the project... But it still shows this error.

**Comment by anhduy5689h** [comment]
I found the root cause. It seems as I capture home_step1.png 2 times and the library threw FileAlreadyExistsException when pulling screenshots from phone to my machine.

**Comment by lyydikoi** [comment]
I have faced same issue. After some investigation, it turned out, that I have provided same name for two different tests:
```
fragmentScenario.onFragment {
    compareScreenshot(it, name = "profileFragment_displayedProperly")
}
```
Shot recorded all screens, but two of them had same name. So, first was loaded, but second failed, cause name existed already.
