### ISSUE TITLE
Could not determine the dependencies of task

### ISSUE THREAD

**Issue by mitsest** [Karumi/Shot#183]
### Expected behaviour
tests should run

### Actual behaviour
gradlew command fails

### Steps to reproduce
I ran ./gradlew productionDebugExecuteScreenshotTests -Precord

and I am getting multiple errors concerning incompatible library versions like androidx.appcompat:appcompat. e.g.
>Dependency path 'app:unspecified' --> 'com.google.android.material:material:1.0.0' --> 'androidx.appcompat:appcompat:1.0.0'
           Dependency path 'app:unspecified' --> 'com.karumi:shot-android:5.4.0' --> 'com.facebook.testing.screenshot:core:0.13.0' --> 'androidx.appcompat:appcompat:1.1.0'
           Dependency path 'app:unspecified' --> 'com.karumi:shot-android:5.4.0' --> 'androidx.compose.ui:ui-test-junit4:1.0.0-alpha07' --> 'androidx.compose.ui:ui-test:1.0.0-alpha07' --> 'androidx.compose.ui:ui:1.0.0-alpha07' --> 'androidx.appcompat:appcompat:1.3.0-alpha01'

Am I missing something?

### Version of the library

5.4.0

**Comment by mitsest** [comment]
gradlew dependencies error log

* What went wrong:
Execution failed for task ':app:dependencies'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[1.2.0
  ]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
  
  Dependency failing: androidx.fragment:fragment-ktx:1.2.0 -> androidx.fragment:fragment@[1.2.0], but fragment version was
   1.3.0-alpha07.

**Comment by mitsest** [comment]
Hi guys, this must be a gradle version issue.

Can you tell me which is the minimum gradle version you support??

I couldn't find it anywhere

**Comment by pedrovgs** [comment]
As you can see in the examples, the minimum gradle version we are using is 6.7.  However, I'm not sure if your issue is related to Gradle 🤔
