### ISSUE TITLE
Execute Screenshot Test runs all instrumented tests.

### ISSUE THREAD

**Issue by osquitoOfTheNorth** [Karumi/Shot#191]
This is more of a question than a bug, but I am wondering if there is a way to configure my shot setup to only run the screenshot tests whenever I run ./gradlew eST .  

Currently I run that command and ALL my instrumented tests will run, which is less than ideal because I am only starting to introduce Screenshot tests to my project and therefore we will have to wait a very long time to get the results of a few Screenshot tests.

### Expected behaviour
Only Screenshot tests run

### Actual behaviour
All instrumented tests (including non screenshot test ones) run

### Steps to reproduce
1. Add shot v. 4.4.0 to classpath
2. apply shot plugin in build.gradle file
3. Specify:  testInstrumentationRunner "com.karumi.shot.ShotTestRunner" in build.gradle file
4. Add required permissions in manifest
5. Create a screenshot test that implements interface:  com.karumi.shot.ScreenshotTest
6. Run screenshot test with  -Pandroid.testInstrumentationRunnerArguments.class and -Precord argument to record result
7. Run screenshot tests with `./gradlew eST` 
8. Observe all instrumented tests being run.

### Version of the library
I am on 4.4.0 so this could be the problem as well.

**Comment by tobiasKaminsky** [comment]
I solved this via having a special annotation "@ScreenshotTest".
Calling then gradlew:
-Pandroid.testInstrumentationRunnerArguments.annotation=com.package.android.utils.ScreenshotTest

With
-Pandroid.testInstrumentationRunnerArguments.class=$class$method
you can even limit it to a special class and/or method.

**Comment by osquitoOfTheNorth** [comment]
Thanks I will take a look at the annotation option! That is very helpful.

**Comment by pedrovgs** [comment]
Thanks @tobiasKaminsky 😃  As you can see @osquitoOfTheNorth, filtering the suite of tests you want to execute is something you can do thanks to the instrumentation runner. There is nothing we can do from our end to provide this feature. You can filter your tests' execution using packages or many other options if you want.

**Comment by AlexKrupa** [comment]
Another solution I found is to use a [JUnit Filter](https://junit.org/junit4/javadoc/latest/org/junit/runner/manipulation/Filter.html) on the `ScreenshotTest` interface provided by Shot (assuming you're using the interface in your tests). That way you don't have to maintain a separate annotation.

A simple implementation looks like this:
```kotlin
class ScreenshotTestFilter : Filter() {

    override fun shouldRun(description: Description): Boolean =
        ScreenshotTest::class.java.isAssignableFrom(description.testClass)

    override fun describe(): String =
        "all tests implementing com.karumi.shot.ScreenshotTest interface"
}
```

Then you pass it as an argument like this:
```sh
./gradlew executeScreenshotTests -Pandroid.testInstrumentationRunnerArguments.filter=com.example.ScreenshotTestFilter
```

---

@pedrovgs is this something you'd consider as "in scope" of Shot? Not as a default behavior, but it seems useful enough to provide (and document) as part of the library. Or perhaps just an example in the documentation would do?

**Comment by stetro** [comment]
In our project we also have both, but we would like to only run each at a time so we use this configuration
```groovy
android {
     ...
     defaultConfig {
         ...
        // only run screenshot instrumented tests when called and vice versa
        if (project.gradle.startParameter.taskNames.any { it.endsWith("ScreenshotTests") }) {
            testInstrumentationRunnerArguments["package"] = "--packagename--tests.screenshot"
        } else {
            testInstrumentationRunnerArguments["notPackage"] = "--packagename--tests.screenshot"
        }
     
     }
}
```

With this `./gradlew connectedAndroidTests` runs instrumented tests only and `./gradlew executeScreenshotTests` run screenshot tests only.
