### ISSUE TITLE
Menu items are not taken as part of the screenshot

### ISSUE THREAD

**Issue by zoubarry** [Karumi/Shot#197]
### Expected behaviour
menu items should been taken as part of the screenshots which comes on top

### Actual behaviour
menu items are not visible from the screenshots

### Steps to reproduce
Create a menu -> open the menu at end of test -> take a screenshot using activity -> menu items not visible

### Version of the library
5.8.0

**Comment by himsachan** [comment]
@zoubarry are you able to solve this issue. I am also facing same challenge.

**Comment by nelson-glauber** [comment]
+1
