### ISSUE TITLE
Provide release build type execution support

### ISSUE THREAD

**Issue by msfjarvis** [Karumi/Shot#202]
### Expected behaviour

Based on this statement from the README:

> **If you are using flavors the available Shot gradle tasks will be configured based on your flavors and build types configuration.**

I expect that both my debug _and_ release build types would be listed on executing `gradle tasks`, so I can opt to run screenshot and instrumentation tests on release builds.

### Actual behaviour

Shot only lists debug build types as valid tasks

### Steps to reproduce

- Apply Shot Gradle plugin to a project
- Run `./gradlew tasks`
- Observe there are no release tasks like `releaseExecuteScreenshotTests`.

### Version of the library

v5.10.0

### Additional information

Combined with [Keeper](https://github.com/slackhq/keeper) running instrumentation tests on release builds is a viable approach and affords the ability to run tests against an APK much closer to what you would release.

**Comment by pedrovgs** [comment]
You are right @msfjarvis When I first implemented the tasks configuration I left the release build type out of the scope because it is not something every team does. I'm adding the tag ``help wanted`` to this issue just in case any external contributor would like to collaborate 😃

**Comment by msfjarvis** [comment]
If you can point me in the general direction of where the task configuration happens then I will be more than happy to send a pull request :)

**Comment by pedrovgs** [comment]
Sure @msfjarvis this is where the magic happens https://github.com/Karumi/Shot/blob/master/shot/src/main/scala/com/karumi/shot/ShotPlugin.scala#L101 Instead of just ignoring the release build type we should check if the release tasks are available in order to link our shot tasks to the release instrumentation task configured by the host project.

**Comment by msfjarvis** [comment]
I didn't get notified that a PR was opened for this so I couldn't review it, but it suffers from the same problem I was facing when I tried implementing it.

In particular, it regresses the case where you **do not** have a custom build type. My app does not implement any custom flavors or build types, just `debug` and `release`. When I apply the plugin, the build first fails because it cannot find a `connectedReleaseAndroidTest` task, and when I set the `android.testBuildType` field to `"release"`, I get the error that `connectedDebugAndroidTest` task is missing.

This will result in the plugin breaking for nearly _every_ user, since it fails for what is considered the "default" build setup.

**Comment by msfjarvis** [comment]
I imagine the publishing task failing is a blessing in disguise that buys time for this to be rectified somehow.

**Comment by msfjarvis** [comment]
I see that you did attempt to account for missing tasks [here](https://github.com/Karumi/Shot/blob/2171fa856629129f21581aaa34f66b637a80e843/shot/src/main/scala/com/karumi/shot/ShotPlugin.scala#L131-L136) but for some reason it's not catching the `org.gradle.api.UnknownTaskException` that's being thrown.

**Comment by msfjarvis** [comment]
Welp, apologies for the rambling. It seems my local build of Shot was somehow broken and task configuration works just fine after a repository pruning and rebuild. Thanks for implementing this feature!

**Comment by pedrovgs** [comment]
Don't worry @msfjarvis 😃  Happy to see the library is working and we've fixed the bug.
