### ISSUE TITLE
NoSuchFileException during record task

### ISSUE THREAD

**Issue by Fishfield** [Karumi/Shot#21]
### Expected behaviour
Screenshots are recorded without any error

### Actual behaviour
the gradle task `./gradlew executeScreenshotTests -Precord` is crashing with a `NoSuchFileException`

>Execution failed for task ':libs:lego:executeScreenshotTests'.
> java.nio.file.NoSuchFileException: C:\R\project\root\libs\lego\screenshots\screenshots-default\com.company.android.ui.components.screenshot.JustAtest_theActivityIsShownProperly.png

### Steps to reproduce
execute gradle command

### Version of the library
0.2.0

### Notes
After checking the folder, the file is not there, but I figured out that there is another folder called "screenshots-default" inside the "screenshots-default" which actually includes the file. So the correct to the file would be C:\R\project\root\libs\lego\screenshots\screenshots-default\screenshots-default\com.company.android.ui.components.screenshot.JustAtest_theActivityIsShownProperly.png

**Comment by pedrovgs** [comment]
Hi @Fishfield this issue could be related with your shot configuration inside your ``build.gradle``. When you configure shot as follows:

```
shot {
    appId = 'YOUR_APPLICATION_ID'
}
```

The ``appId`` value is used to search your screenshots and maybe there is something wrong with your configuration 😃  Could you share your build configuration?

**Comment by Fishfield** [comment]
Hey @pedrovgs sorry for the late response, but I only have time once every 2 months to work on stuff which is not related to our daily business in the company. I attached the build gradle so you can have a look at it.
[build_gradle.txt](https://github.com/Karumi/Shot/files/1405993/build_gradle.txt)

It seems if I add the configuration for the facebook lib:

`screenshots {
	screenshotTestPackage "com.runtastic.android.ui.components.screenshot"
}`

I get the error. If I don't add this line, I get a different one:

`com.android.builder.testing.ConnectedDevice > No tests found.[Pixel - 8.0.0] FAILED 
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).
:libs:lego:connectedDebugAndroidTest FAILED`

Here is the test [test.txt](https://github.com/Karumi/Shot/files/1406012/test.txt)
So do you have any glue, where this weird package is coming from (`com.android.builder.testing`)? What does the `appId` actually mean, is it the package where the tests are located at?

**Comment by pedrovgs** [comment]
Hi @Fishfield the error you are facing seems could be derived from different errors:

* The instrumentation test runner is not properly configured.
* The tests you've written are not inside the ``androidTests`` folder where the instrumentations should be placed.
* Your app has configured different flavors but you are not configured shot properly using indicating the flavor you use to run your tests:

```
  shot {
    appId = 'YOUR_APPLICATION_ID'
    instrumentationTestTask = 'connected<FlavorName><BuildTypeName>AndroidTest'
    packageTestApkTask = 'package<FlavorName><BuildTypeName>AndroidTest'
  }
```

I've seen you've configured the original plugin and the error is now different and the error is different now so I guess it's related to your project configuration.

The error ``com.android.builder.testing`` is related to the Android Gradle plugin trying to execute your instrumentation tests using ADB.

If you could create a simple repository reproducing the error that could help us to reproduce and fix the issue. We are using this plugin in several projects and we can't reproduce this issue. [Here you have a repository using this plugin](https://github.com/Karumi/KataScreenshotKotlin)

**Comment by pedrovgs** [comment]
@Fishfield did my previous comment help you to fix the issue you were facing?

**Comment by rm8x** [comment]
I may have a workaround:
-delete the `app->build->reports->shot` and `app->screenshots` folders.
-In Android Studio do `file->invalidate caches and restart`.

I was getting the same error when the task was looking for `metadata.xml` inside `screenshots-default` folder. Somehow things were being saved to `screenshots-default/screenshots-default` so that is where `metadata.xml` was. I had several successful runs with no problems prior to encountering this.
