### ISSUE TITLE
Shot tests for compose fail on emulator with API level >=29 

### ISSUE THREAD

**Issue by vanpra** [Karumi/Shot#214]
### Expected behaviour
The shot tests should execute/record screenshots successfully on devices with API level >= 29

### Actual behaviour
All tests fail with the following error
```
java.io.IOException: No such file or directory
at java.io.UnixFileSystem.createFileExclusively0(Native Method)
```

### Steps to reproduce
1. Add a compose UI test which uses `compareScreenshot`
2. Run test on an emulator with API level >= 29

### Version of the library
5.10.3

**Comment by pedrovgs** [comment]
@vanpra I can ensure it is working. Please review your config and ensure you follow the set up process step by step.

**Comment by MyDogTom** [comment]
@vanpra Did you find what was missing in your configuration?
