### ISSUE TITLE
Karumi shot 5.10.3 not working on test lab

### ISSUE THREAD

**Issue by xyzwilliamxyz** [Karumi/Shot#216]
Hi!

we are trying to run screenshot tests in our testlab environment. We were using version *3.1.0* and it was taking screenshots of only some parts of the screen. 

As we saw, there was a PR that entered Karumi Shot on 2019 that fixed things to work on testlab, so we thought that upgrading it to the latest version (5.10.3) would solve the problem, but now we're getting this exception:

`
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-3
     FATAL EXCEPTION: Instr: com.example.TestApplicationRunner
Process: com.example, PID: 13508
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-3
	at org.kxml2.io.KXmlSerializer.endTag(KXmlSerializer.java:519)
	at com.facebook.testing.screenshot.internal.AlbumImpl.endXml(AlbumImpl.java:111)
	at com.facebook.testing.screenshot.internal.AlbumImpl.flush(AlbumImpl.java:80)
	at com.facebook.testing.screenshot.internal.ScreenshotImpl.flush(ScreenshotImpl.java:158)
	at com.facebook.testing.screenshot.ScreenshotRunner.onDestroy(ScreenshotRunner.java:51)
	at com.karumi.shot.ShotTestRunner.finish(ShotTestRunner.kt:19)
	at com.example.TestApplicationRunner.finish(TestApplicationRunner.kt:22)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:404)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
`

apparently we followed the setup correctly. Does anyone know what it coulbe be?

**Comment by pedrovgs** [comment]
Hey @xyzwilliamxyz that exception looks like you've changed something on the usage of the library. We've introduced a lot of changes since 3X version. Are you using ``ScreenshotTest`` interface to take your screenshots?

**Comment by xyzwilliamxyz** [comment]
Hi @pedrovgs , thanks for the reply!

It was indeed misconfiguration, I had to update the test runner + add testApplicationId and now it's executing the tests properly :D

However, for some reason, it's not taking screenshots anymore when it runs on test-lab (it used to take on version 3). I'm not sure if there's a different way of doing this, but we were executing it from our pipeline with:

`gcloud firebase test android run` 

and apparently it would detect our ScreenshotRunner and take screenshots. Do you guys have any guidance on this?

**Comment by xyzwilliamxyz** [comment]
Hi @pedrovgs, thanks for your support! We managed to find a way to make it work by making some tweaks on our test lab command line and now it's working as intended. We can close this issue.

**Comment by huwdfj** [comment]
Hi @xyzwilliamxyz it sounds like you have got Shot working via the Firebase Test lab? Could you provide some details on your workflow and which gradle tasks you run where?
I can get simple png files from the Test Lab runs but I am unsure what to run to generate the metadata files and the other png files that seem to be required for the comparison. Thanks in advance.

**Comment by SumeraMartin** [comment]
Hi, @xyzwilliamxyz  I'm curious about the same thing as @huwdfj did you find a solution to this problem?
