### ISSUE TITLE
No Screenshot moved to screenshots/debug

### ISSUE THREAD

**Issue by andretortolano** [Karumi/Shot#219]
Im trying to use shot in my project and for some reason I'm unable to get a screenshot into screenshots/debug folder

When I look inside Build/ there is a lot of small pieces of images so I`m not sure whats going wrong here

if someone could take 5 minutes to checkout my project and see if this is something I'm missing or if its an actual problem of the lib, Thanks!

https://github.com/andretortolano/desafio-android  (task/shot)

### Steps to reproduce
Please check my project on branch task/shot

### Version of the library
5.10.4

**Comment by oluwasanmiAderibigbePapershift** [comment]
Same here. I am currently experiencing this issue

**Comment by oluwasanmiAderibigbePapershift** [comment]
I tried setting up again and it works for me now. @andretortolano  Try setting it up again?

**Comment by andretortolano** [comment]
@oluwasanmiAderibigbePapershift are you on windows by any chance? I think my problem is related to the OS I'm using, I also noticed other issues related to windows

**Comment by pedrovgs** [comment]
Closed because it is duplicated by #140
