### ISSUE TITLE
Not all screenshots are captured

### ISSUE THREAD

**Issue by mkubele** [Karumi/Shot#220]
Hi, I'm quite desperate now. I have a class with multiple screenshot tests of different activities, but screenshots from only test are captured and downloaded from the device. I initially thought it's a bug in the shot library, so I prepared sample app with the same settings, but it works fine there.
Do you have any idea what might be wrong?
sample app:
![Screenshot 2021-04-20 at 13 31 26](https://user-images.githubusercontent.com/34385616/115456918-06b54f00-a224-11eb-9393-34bc05b5ea02.png)
production app:
![Screenshot 2021-04-20 at 13 31 05](https://user-images.githubusercontent.com/34385616/115456926-087f1280-a224-11eb-9641-766d6cb39dd0.png)

### Expected behaviour
All screenshots are captured and downloaded.

### Actual behaviour
Screenshots from one random test are captured and downloaded.

### Steps to reproduce
I'm not able to reproduce it in sample app, to be honest.

### Version of the library
5.10.4

**Comment by ddudek** [comment]
do you use orchestrator in your project?

**Comment by mkubele** [comment]
Yes, I do use it.

**Comment by ddudek** [comment]
It's not supported at the moment https://github.com/Karumi/Shot/issues/78

**Comment by mkubele** [comment]
Thanks for the info. It might be useful to mention it in the readme :)

**Comment by iadcialim** [comment]
@mkubele did u find another way to clear cache so this lib can take multiple screenshots?

**Comment by mkubele** [comment]
@iadcialim I added switch to turn off the orchestrator if needed
`
testOptions { execution = if (disableOrchestrator()) "HOST" else "ANDROIDX_TEST_ORCHESTRATOR" }

fun disableOrchestrator(): Boolean {
    val prop = findProperty("disableOrchestrator") as? String
    return prop != null
}
`
