### ISSUE TITLE
Support for androidx orchestrator (bump up com.facebook.testing.screenshot:core to 0.14.0)

### ISSUE THREAD

**Issue by ddudek** [Karumi/Shot#223]
Facebook screenshot lib just announced support for androidx orchestrator in 0.14.0. Looks like shot still uses 0.13.0 which causes it incompatible with the orchestrator. The outcome is that only last screenshot is retrieved, discarding all previously run tests (e.g. https://github.com/Karumi/Shot/issues/78).

Would it be hard to bump up the facebook library and maybe with minumum effort make Shot also support orchestrator?

### Expected behaviour
When orchestrator is turned on, all screenshots are recorded, verified and included in the raport.

### Actual behaviour
Only screenshot from the test that was run as last is included in the raport.

### Steps to reproduce
use android orchestrator:
```
android {
  testOptions {
    execution 'ANDROIDX_TEST_ORCHESTRATOR'
  }
}
```
run shot screenshot tests

### Version of the library
5.10.4

**Comment by pedrovgs** [comment]
This issue duplicates https://github.com/Karumi/Shot/issues/78. I'm closing it.
