### ISSUE TITLE
Tolerance calculation seems wrong when content is misplaced

### ISSUE THREAD

**Issue by andreroggeri** [Karumi/Shot#226]
### Expected behaviour
It should fail the test when the content position is changed when tolerance is configured

### Actual behaviour
The test pass with a warning that there is a 0.0 % difference of pixels

![image](https://user-images.githubusercontent.com/6232673/118290583-fa33b780-b4ac-11eb-94a3-e451d17c97cb.png)

### Steps to reproduce
I used the `shot-consumer` project
1. Update the `simple_fragment.xml` changing the `layout_gravity` to `top`
2. Set the tolerance to 0.000001 on the `build.gradle` file
3. Run the tests and check the result

### Version of the library
5.10.4

**Comment by andreroggeri** [comment]
I did some digging and it seems that the problem is on this line:

https://github.com/Karumi/Shot/blob/100477e492b839c8a74372a2aec46b068b713ca4/core/src/main/scala/com/karumi/shot/screenshots/ScreenshotsComparator.scala#L49

_Disclaimer: I never touched scala_

From what I researched, the diff method doesn't consider the element position on the array, so an Image with the same pixels but on different order would pass on the check

**Comment by leandroxt** [comment]
In the project I'm working, I'm having the same problem.

**Comment by JuzTosS** [comment]
I'm having the same issue

**Comment by andreroggeri** [comment]
Hey @pedrovgs could you please take a look at my PR ?

**Comment by pedrovgs** [comment]
Thank you so much for your help @andremion I'm releasing a new version with the fix right now.

**Comment by pedrovgs** [comment]
New version released @andremion please let me know if everything is working fine for you with version 5.10.6.

**Comment by andremion** [comment]
@pedrovgs , I think you mixed up the Andres 😅
