### ISSUE TITLE
Toggling `runInstrumentation` from the commandline

### ISSUE THREAD

**Issue by SamCosta1** [Karumi/Shot#228]
More of a feature request than an issue! (which I'll happily do and PR if there's no pushback)

### Expected behaviour
`./gradlew debugScreenshotTest -PrunInstrumentation=true|false`

Would toggle the running of instrumentation tests on and off. This would be really useful for our automated jobs since we could configure our CI system to run without instrumentation, without needing to modify the gradle config.

### Actual behaviour

`runInstrumentation` is ignored from the commandline.

It would be brill to be able to override the config in the gradle file with the commandline argument.

Version: 5.10.4

**Comment by pedrovgs** [comment]
Yeap you are right @SamCosta1 it is broken. I think I broke it when I changed part of the plugin configuration. Could you please take a look at this one? If you can't fix it I'll fix it by myself 😃  Thank you in advance!

**Comment by SamCosta1** [comment]
Will do!
