### ISSUE TITLE
5.10.5 Uses compose on projects without it (cannot find symbol)

### ISSUE THREAD

**Issue by chrisjenx** [Karumi/Shot#232]
### Expected behaviour
Should be able to assemble tests without depending on compose manually

### Actual behaviour
/home/chris/git/.../OmegaInfoScreenActivityTest.java:53: error: cannot find symbol
    androidx.compose.ui.test.SemanticsNodeInteraction node, @org.jetbrains.annotations.Nullable()
                            ^
  symbol:   class SemanticsNodeInteraction
  location: package androidx.compose.ui.test/home/chris/git/.../OmegaInfoScreenActivityTest.java:59: error: cannot find symbol
    androidx.compose.ui.test.junit4.ComposeTestRule rule, @org.jetbrains.annotations.Nullable()
                                   ^
  symbol:   class ComposeTestRule
  location: package androidx.compose.ui.test.junit4

### Steps to reproduce
Gradle 7.0.2
ASG 4.2.1
Kotlin 1.5.10
Shot 5.10.5

```
@RunWith(AndroidJUnit4::class)
class OmegaInfoScreenActivityTest : ScreenshotTest {
}
```

### Version of the library
Shot 5.10.5

**Comment by pedrovgs** [comment]
Hey @chrisjenx could you please share your shot configuration? The plugin adds compose as a transitive dependency but it should be working on projects without compose installed. Actually, the sample projects in this repository show the plugin is working. Did you change something in your Shot config? Did you exclude compose dependencies?

**Comment by chrisjenx** [comment]
Honestly not sure why it failed before, I upgraded again and now it works, guessing there was some caching issues...

**Comment by lyydikoi** [comment]
I'm facing currently the same issue.
When I have the same Test dependencies, as in the sample project, all works good (except I can't set up Dagger injection for test.)
When I add 

`kaptAndroidTest("com.google.dagger:dagger-compiler:$daggerVersion")`

and run tests, I get:
```
symbol:   class SemanticsNodeInteraction
  location: package androidx.compose.ui.test/Users/.../ProfileLegendFragmentTest.java:50: error: cannot find symbol
    androidx.compose.ui.test.junit4.ComposeTestRule rule, @org.jetbrains.annotations.Nullable()
                                   ^
  symbol:   class ComposeTestRule
  location: package androidx.compose.ui.test.junit4[WARN] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: android.databinding.annotationprocessor.ProcessDataBinding (DYNAMIC).
```

Could you provide any info, please, how can I work around this?

**Comment by josehector** [comment]
@lyydikoi I had the same error. I will be able to fix it added ....
`androidTestImplementation "androidx.compose.ui:ui-test-junit4:1.0.0-beta03"`

@pedrovgs is it possible that the plugin doesn't add the compose as a transitive dependency?

**Comment by pedrovgs** [comment]
@josehector Shot adds ` implementation "androidx.compose.ui:ui-test-junit4:1.0.0-beta03"`` as a transitive dependency. If you check the sample projects it should work out of the box.
