### ISSUE TITLE
com.google.android.gms.maps.MapView screenshot transparent

### ISSUE THREAD

**Issue by souissihaythem** [Karumi/Shot#234]
hello,

I have a problem when I get the screenshot of a fragment that contain a  MapView. The map view is transparent.

Screennshot using KarumiShot
![AdvertFullScreenMapFragmentTest__Google_Android SDK built for x86](https://user-images.githubusercontent.com/2062107/120722854-cf97b600-c4d0-11eb-91e2-15e7b66df6e1.png)

Screenshot using the phone (the map appear correctly
![Screenshot_1622760198](https://user-images.githubusercontent.com/2062107/120722911-ed651b00-c4d0-11eb-85a3-4cfe0ed6eb24.png)

Here is my test code:

```
class AdvertFullScreenMapFragmentTest: ScreenshotTest {

    @Test
    fun launchFragment() {
        val bundle = Bundle().apply {
            putString(BUNDLE_ADVERT_LOCATION, "loc")
            putString(BUNDLE_ADVERT_PRICE, "price €")
        }
        val fragment = launchFragmentInContainer<AdvertFullScreenMapFragment>(factory = object : FragmentFactory() {
            override fun instantiate(classLoader: ClassLoader, className: String): Fragment {
                return AdvertFullScreenMapFragment()
            }
        }, fragmentArgs = bundle, themeResId = R.style.AppTheme).waitForFragment()

        // wait until map load
        Thread.sleep(10000)

        compareScreenshot(fragment)
    }
}

```

Any idea why this doesn't work with MapView (com.google.android.gms.maps.MapView)?

**Comment by pedrovgs** [comment]
Right now the library we use under the hood when using plain old ``MapView`` components don't work. You can review the details [here](https://github.com/facebook/screenshot-tests-for-android/issues/55). I'm afraid until this feature is fixed on their end we won't be able to provide support for maps. I'm sorry.
