### ISSUE TITLE
How to make shot work on your custom test runner similar to facebook's screenshot lib?

### ISSUE THREAD

**Issue by carlo-oropesa** [Karumi/Shot#236]
### Overview
I understand that shot has it's own runner but is there a way to use my own custom runner instead of using the default? On facebook's android-screenshot library there is a workaround on this one by overriding setup and teardown hooks
https://facebook.github.io/screenshot-tests-for-android/#getting-started

**Comment by pedrovgs** [comment]
Hey @carlo-oropesa can't you just create your own test runner extending from ``ShotTestRunner`` and add your code there? I've done it for different apps when we need, for example, to use dex opener or any other library and it worked for me.
