### ISSUE TITLE
Configure HTML report to just show SS comparison for failed tests

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [Karumi/Shot#24]
### Expected behaviour

Would be nice to provide a configurable property to allow users fetching the lib to just show screenshot comparisons under the HTML report for failed tests (since comparing the ones for green tests can be a bit irrelevant).

### Actual behaviour

It's showing screenshot comparison for both, passing and non-passing tests.

### Steps to reproduce

Run screenshot tests by command line and check the HTML report.

### Version of the library

`0.2.0`

PD: The new HTML report is helpful! That's exactly the thing you want to have on CI for failing tests. Thanks for adding the feature.

**Comment by pedrovgs** [comment]
👍

**Comment by alexanderbezverhni** [comment]
Hi @pedrovgs . What do you think on showing first failed tests, and passed tests afterwards? We have 200 tests in our screenshot tests suite, and when 1 test fails - it's challenging to find it from the long list.

I agree that failed tests are of much higher interest, than passed ones. Showing first failed tests makes sense. I can make it happen in a `PR`, WDYT?

**Comment by pedrovgs** [comment]
That'd be awesome @alexanderbezverhni! The change is minimum because you only need to sort the list before rendering the result 😃 I think it could be nice contribution if you can send a PR with the change!

**Comment by alexanderbezverhni** [comment]
@pedrovgs https://github.com/Karumi/Shot/pull/74
