### ISSUE TITLE
Is it possible to ignore certain areas for comparison?

### ISSUE THREAD

**Issue by rakesh-sh2020** [Karumi/Shot#241]
I can't see anything in the docs but what I would like to do is mark certain parts of the reference image as not required for comparison.

This way fields like timestamps/random/indeterminate fields can be excluded.

**Comment by tobiasKaminsky** [comment]
I could also find not such things.
In Selenium there was the possibility to set the area to transparent, so that comparison in this area always was successful.
With Shot I "simply" remove those UI elements via setting visibility to hide.

**Comment by pedrovgs** [comment]
🤔 I remember we have something for this. Depending on the UI framework you are using this feature is already implemented or not. If you are using compose we don't have this feature, if you are using the old Android SDK you can define the views you want to make invisible before taking the screenshot. This is the property you have to [define](https://github.com/Karumi/Shot/blob/master/shot-android/src/main/java/com/karumi/shot/ScreenshotTest.kt#L36)

However, there are some scenarios where this can affect your layout. The framework will [make the views invisible](https://github.com/Karumi/Shot/blob/master/shot-android/src/main/java/com/karumi/shot/ScreenshotTest.kt#L163), and this would maybe not work for your scenario.
