### ISSUE TITLE
Error:Configuration with name 'androidTestImplementation' not found.

### ISSUE THREAD

**Issue by CristianGM** [Karumi/Shot#25]
### Expected behaviour
When using the Android gradle plugin <3.0 the plugin should use `androidTestCompile`

### Actual behaviour
it's adding `androidTestImplementation` so it doesn't compile

The issue seems to be in that function
https://github.com/Karumi/Shot/blob/adeef269ab719ffa776b96d50d7928c0c2b96fa8/shot/src/main/scala/com/karumi/shot/ShotPlugin.scala#L82

### Steps to reproduce
Apply the plugin to a project using Gradle 4.2.1 but Android plugin 2.3.3

### Version of the library
0.3.0

**Comment by flipper83** [comment]
@CristianGM can you share with me in the gradle.properties thebuild:gradle? is 2.3.3 ??

**Comment by CristianGM** [comment]
In the build.gradle I have:
`  classpath 'com.android.tools.build:gradle:2.3.3'`

but in the gradle-wrapper.properties
```
#Wed Oct 18 17:13:00 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.2.1-all.zip
```

The issue is the new implementation/api dependencies comes with the `'com.android.tools.build:gradle:3.+'` not with the gradle wrapper you are checking.

**Comment by pedrovgs** [comment]
Sorry for the delay @CristianGM, but I've been out for holidays 🛫  Could you paste a link to the Gradle Android Plugin changelog so we can review if the breaking change was added in this version or a different one? @flipper83 reviewed the version number when implementing the feature and if it was applied in the Android Plugin or Gradle twice, but it was long ago and I don't remember the numbers. If you could provide the links I'll personally fix the issue for the next version. Thank you in advance 😃

**Comment by pedrovgs** [comment]
@CristianGM could you review this issue you opened? I'd really like to fix it but I need the information I requested you in my previous comment 😃

**Comment by CristianGM** [comment]
I did move to AGP 3.0 so I don't have the issue anymore.
I could simply close the issue, also I don't expect many people will use AGP 2.3.x , fixing it would be just for correctness.

**Comment by pedrovgs** [comment]
Ok, thanks! 😃
