### ISSUE TITLE
Print feedback when a screenshot doesn't match

### ISSUE THREAD

**Issue by Serchinastico** [Karumi/Shot#27]
There are situations where we aren't able to access CI environments where tests are executed. That means that if a test fails we don't have any way to know what are the differences with the reference screenshot. The easiest fix for this sort of problems is to watch for failing tests and print a base64 of the new screenshot so that we can easily decode it in our machines and effectively see what changed. This feature should only run on CI environments and as such, Shot should provide an opt-in preference to enable it.

**Comment by pedrovgs** [comment]
Thanks for creating the issue @Serchinastico. There are some points we should take into account:

* This feature should be disabled by default.
* The README should reflect the usage of this feature.
* If possible, we should show the image using a tool like [this one](https://github.com/stefanhaustein/TerminalImageViewer). Even when the result is not the best possible it could be useful. I don't know if there is any other tool.

**Comment by pedrovgs** [comment]
@Serchinastico I'm implementing the diff feature right now. I guess you'd like to print the base 64 of the diff generated. Let me know if you need help when working on this. I'll try to release a new release at the end of the day.

**Comment by Serchinastico** [comment]
I think printing either the diff or the new screenshot are both good ideas. I personally have been using the newly created screenshot just because I didn't have access to the diff'ed image before but that ended up being quite usable IMO.

**Comment by pedrovgs** [comment]
Let's see at the end of the day, once I publish the PR if we prefer the diff or the new screenshot taken. I think the diff is going to be more interesting.
