### ISSUE TITLE
Show fallback image when the reference screenshot is missing

### ISSUE THREAD

**Issue by Serchinastico** [Karumi/Shot#32]
### Expected behaviour

Show a fallback image when there is no reference image to compare with in the HTML report.

### Actual behaviour

When the reference image is missing we are showing a broken link in the HTML report.

### Steps to reproduce

Create a new screenshot test in your application and run screenshot tests with shot by executing `gradle executeScreenshotTests`. The  HTML report will show a broken link like the image below (ignore the gray rectangles 😅 ):

![slice](https://user-images.githubusercontent.com/3116415/34985285-db2feb12-fab3-11e7-9745-c59c3cd43936.png)

### Version of the library

1.0.0

**Comment by pedrovgs** [comment]
We can just leave an empty image. The bug is in the template generation. It assumes the file is there when it's not. This should be really simple to fix 😃

**Comment by pedrovgs** [comment]
This was fixed long ago showing an empty image but I forgot to close the issue.
