### ISSUE TITLE
Shot doesn't work with API 23+ devices

### ISSUE THREAD

**Issue by AOrobator** [Karumi/Shot#35]
### Expected behaviour
Screenshot tests run on API 23+

### Actual behaviour
```com.example.screenshottest.ExampleInstrumentedTest > takeScreenshot[Nexus 6P - 8.1.0] FAILED 
        java.lang.RuntimeException: This does not currently work on API 23+, see https://github.com/facebook/screenshot-tests-for-android/issues/16 for details.
        at com.facebook.testing.screenshot.internal.ScreenshotDirectories.checkPermissions(ScreenshotDirectories.java:38)
```

### Steps to reproduce
run ./gradlew executeScreenshotTests -Precord

### Version of the library
1.0.0

Just a note, the facebook screenshot library now supports API 23+

https://github.com/facebook/screenshot-tests-for-android/pull/89

**Comment by pedrovgs** [comment]
Thanks for reporting @AOrobator. As the latest Facebook release is recent I did not see this feature. I'll update Shot to support this feature for sure 😃

**Comment by pedrovgs** [comment]
Fixed! I'm going to release a new version today @AOrobator

**Comment by pedrovgs** [comment]
Thanks @tonilopezmr and @Serchinastico 😃
