### ISSUE TITLE
Running Across Multiple Devices

### ISSUE THREAD

**Issue by pranayairan** [Karumi/Shot#40]
### Expected behavior
Facebook Screenshot test supports running on multiple devices https://facebook.github.io/screenshot-tests-for-android/ with this flag 
`screenshots {
  // ...
  multipleDevices true
}`
But I don't see the same option when using Shot. 
### Actual behaviour
Shot has support for multipleDevices with gradle flags

### Version of the library
com.karumi:shot:2.0.0

**Comment by pedrovgs** [comment]
Hi @pranayairan this could be a killer feature but it is not trivial at all. It is directly related to how our plugin uses adb and compares the images using different sources. It could be great if you or any other developer would like to contribute 😃 I'm marking this issue as ``enhancement`` and ``help wanted``  .

**Comment by loveshjain** [comment]
Hi @pedrovgs @pranayairan Did you guys find out how to Shot supports running on multiple devices

**Comment by pedrovgs** [comment]
Nope from my side. You should modify our Gradle plugin to list the available devices and download the images from different folders. You should also change how images are saved so the name of the file does not collide. This is a killer feature but it's not easy to implement at all.

**Comment by pedrovgs** [comment]
I've sent a PR providing support for this feature.
