### ISSUE TITLE
Update Faceebook library

### ISSUE THREAD

**Issue by pedrovgs** [Karumi/Shot#42]
As you can see [here](https://github.com/facebook/screenshot-tests-for-android/releases), Facebook published new releases of their library so it is time to update the library on our side.

**Comment by diegolucasb** [comment]
@pedrovgs, I'd like to contribute to the project working on this issue, but I'm a bit lost in how to start. Do you have any guide which can help me with it?

**Comment by pedrovgs** [comment]
Hi @diegolucasb! You just need to update [this version](https://github.com/Karumi/Shot/blob/master/core/src/main/scala/com/karumi/shot/domain/model.scala#L22) number and check everything is working as expected.

For testing the lib manually you can execute ``./gradlew install`` and after that run the screenshot tests from the Android consumer project.
