### ISSUE TITLE
Add support for Spoon

### ISSUE THREAD

**Issue by loveshjain** [Karumi/Shot#47]
I am trying to use Shot with Spoon by configuring

**shot {
    appId = "<applicationID>"
    instrumentationTestTask = "spoonNormalDevDebugAndroidTest"
    packageTestApkTask = "packageNormalDevDebugAndroidTest"
}**

but when I run the task `./gradlew executeScreenshotTests -Precord` it is throwing 

> > Task :app-gomoney:executeScreenshotTests FAILED
> 💾  Saving screenshots.
> 
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app-gomoney:executeScreenshotTests'.
> > java.io.FileNotFoundException: path of directory/screenshots/screenshots-default/metadata.xml (No such file or directory)

However it works fine with

**shot {
    appId = "<applicationID>"
    instrumentationTestTask = "connectedNormalDevDebugAndroidTest"
    packageTestApkTask = "packageNormalDevDebugAndroidTest"
}**

Could you please let me know what bit I am missing.

Many thanks in advance.

**Comment by pedrovgs** [comment]
Hi, @loveshjain by default our Gradle plugin doesn't' support Spoon multiple devices features. This is something we'd need to implement. This could be a nice enhancement but we don't have time to implement such a big feature by ourselves right now. Feel free to contribute to the project if you think you can help us!

**Comment by loveshjain** [comment]
Hi @pedrovgs Thanks for the reply. Actually I am not trying to run test across multiple devices. Instead I am running it only on one device but with Spoon. Since Spoon is what we are using which gives a nice HTML report as well. 

Since we running automation suite for feature builds, PR builds and master. I want to implement Screenshot testing for feature builds only at the moment where we can restrict it to 1 device but with spoon.

**Comment by pedrovgs** [comment]
I'm afraid I have to close this issue. After checking what was going on with spoon I've noticed the Facebook library we use under the hood doesn't support spoon for now. However, we've added support for Composer which is a really nice alternative to spoon 😃
