### ISSUE TITLE
Upgrade to newest Gradle Version

### ISSUE THREAD

**Issue by kshirsagarps** [Karumi/Shot#50]
### Expected behaviour
executeScreenshotTests should not return error with new gradle plugin.

### Actual behaviour
I've updated my project to new android gradle plugin 3.2.1 and have updated gradle to version gradle-4.10.2. But, when I run executeScreenshotTests, the task exits with an error status.
I also get an error - 
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
```
### Steps to reproduce
I am running the task in a shell script and enclosed in a trap to catch any non zero exit status.

### Version of the library
V2.1.1

**Comment by pedrovgs** [comment]
We will have to take a look at the API we are using right now. @kshirsagarps could you send a PR updating the Android consumer we've written inside this repository? This would be really helpful in order to reproduce the issue and find where the error is. Thank you so much in advance.

**Comment by pedrovgs** [comment]
I'm closing this issue. [This PR](https://github.com/Karumi/Shot/pull/59) shows how an Android consumer with the latest Gradle version is working properly.

**Comment by mitsest** [comment]
So now the minimum supported gradle version is 5.4.1?
