### ISSUE TITLE
Release Shot 2.3.0

### ISSUE THREAD

**Issue by farukprogrammer** [Karumi/Shot#60]
I want to use multiple device but it needs version 2.2.1-SNAPSHOT

### Expected behaviour
We can use version 2.2.1-SNAPSHOT

### Actual behaviour
The latest version still 2.2.0

**Comment by pedrovgs** [comment]
Hi @faruqy87 we have some tasks pending before publishing the final release. You should be able to use the new 2.3.0 release before August. Sorry for the inconveniences.

**Comment by faruqy87** [comment]
Hi, Thank you so much for the fast response. I've already solved it by building in my mavenLocal and try the **multiple device** feature. From my experiment there is some point that I need to clarify : 

-  It seems it just divides the test across multiple emulators (with the same density) randomly. 

-  It's not separating the screenshots into each device folder. 

- The newest version of **composer** need Gradle version 5.4.1 or above, please note it in the documentation

Is it possible to run all tests in each device separately? By doing that, we can remove "the same density" restrictions. But maybe it will be hard for the verification process and reporting theme.

But overall, thank you for the hard work, I really like this library so much.

**Comment by pedrovgs** [comment]
Hi @farukprogrammer, I've updated the documentation to clarify these points. The feature is designed to run our screenshot tests between different devices so we can reduce the execution time. This helps a lot when running your have huge code coverage. The screenshots taken will not be separated into different folders because we don't need it for this feature. I've updated the readme to specify you need Gradle 5.4.1 or above to use composer.

**Comment by pedrovgs** [comment]
I forgot to mention, I've just released the version 3.0.0. So I'm closing this issue. Thanks for your feedback!

**Comment by iadcialim** [comment]
> Hi @farukprogrammer, I've updated the documentation to clarify these points. The feature is designed to run our screenshot tests between different devices so we can reduce the execution time. This helps a lot when running your have huge code coverage. The screenshots taken will not be separated into different folders because we don't need it for this feature. I've updated the readme to specify you need Gradle 5.4.1 or above to use composer.

Hi @pedrovgs  do you think the team will support running and verifying screenshots on multiple devices?
This is not to reduce test execution time but to test/compare screenshots on different devices at the same time.
This is also mean that I need to prepare screenshots for these devices beforehand as the basis of truth.

**Comment by pedrovgs** [comment]
I'm afraid this is something we are going to implement in the short term :(

**Comment by iadcialim** [comment]
Sorry, I don't get you. "in the short term" means?

**Comment by pedrovgs** [comment]
My previous comment means that right now we are working on different features and our resources are limited. I'd love to implement a lot of different features for Shot but my time is limited and we don't have external contributors for now working on big features like this one. Would you be open to implementing this solution by yourself @iadcialim ?
