### ISSUE TITLE
Build failure after upgrade to Gradle 3.5.0

### ISSUE THREAD

**Issue by Philio** [Karumi/Shot#63]
### Expected behaviour

Gradle sync completes

### Actual behaviour

Gradle sync fails with Gradle plugin 3.5.0

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/phil.bayfield/***/***/screenshot/build.gradle' line: 13

* What went wrong:
A problem occurred evaluating project ':screenshot'.
> Failed to apply plugin [id 'shot']
   > Extension not initialized yet, couldn't access compileSdkVersion.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':screenshot'.
> compileSdkVersion is not specified.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 3s
Extension not initialized yet, couldn't access compileSdkVersion.
```

Line 13 is: `apply plugin: 'shot'`

### Steps to reproduce

Upgraded Gradle plugin from 3.4.2 to 3.5.0

### Version of the library

2.2.0 (tried 3.0.0 but had issue #62)

**Comment by pedrovgs** [comment]
Thanks for reporting. I won't have time to review this until the middle of September. However, if you think you can find where the error is please let me know.

**Comment by japplin** [comment]
I had the same issue, I fixed it by moving my apply plugin line below the android block in build.gradle

**Comment by durbon** [comment]
Confirmed. The problem is solved putting the apply plugin below the `android` block that has the compileSdkVersion needed. It looks 3.5.0 needed this value before

**Comment by Philio** [comment]
Turns out that worked for me too. Didn't have time to check before so had just reverted the plugin upgrade but moving the `apply plugin` was all that was needed.

**Comment by pedrovgs** [comment]
Thank you so much @Philio and @durbon. As you mentioned before moving the plugin after the android configuration blog is a valid workaround. Additionally, I've updated the code to support that gradle version. We'll release a new version with this fix as soon as the PR is approved. Shot 3.0.2 will contain the fix you need to be able to use the Android Gralde plugin 3.5.X and Shot 😃

**Comment by allenarduino** [comment]
Another error pops up after moving the ``` apply plugin ``` below the android block.
This error shows:
```
Could not find method android() for arguments [react_3mo7jrvccre361ao42njv43bl$_run_closure5@4ef5f6d2] 
on project ':app' of type org.gradle.api.Project.
```
