### ISSUE TITLE
Multi-test record issues

### ISSUE THREAD

**Issue by chengbooxup** [Karumi/Shot#64]
Hi,

I used : executeScreenshotTests -Precord --stacktrace -Pandroid.testInstrumentationRunnerArguments.class=<com.your.package.ClassTest> to record all tests in this class

in each test at the end of the test : 
 Screenshot.snapActivity(activity).record()

But only the last test is uploaded to /screenshots
Expected behaviour : all tests should be recorded

Version of the library : 2.2.0

I found : before execute a test, the folder in emulator sdcard/screenshots/appid.test/ is earsed

**Comment by pedrovgs** [comment]
Hi @chengbooxup I don't understand how this could be possible. Could you create a GitHub repository reproducing the issue so we can take a look at this bug?

**Comment by chengbooxup** [comment]
Hi @pedrovgs, I will create a Github repository ASAP with copy all project configurations

**Comment by pedrovgs** [comment]
Thanks!

**Comment by chengbooxup** [comment]
HI @pedrovgs, sorry about all, i rechecked my configuration, the problem comes from Jacoco configuration, il erases every execution of tests.

good job for shot.

I will close this pull request

**Comment by madyx** [comment]
I have the issue when using
`
android {
    testOptions {
        execution 'ANDROIDX_TEST_ORCHESTRATOR'
    }
...
}
`
I also tried with `testInstrumentationRunnerArguments clearPackageData: 'false'` but the screenshots are cleared after each run test method.

**Comment by pedrovgs** [comment]
@madyx please create a demo repository where we can reproduce the error and feel free to open a new issue with all the information you can give us about the error.

**Comment by tobiasKaminsky** [comment]
This is happening also on our project, e.g. here: 
https://github.com/nextcloud/android/pull/5378/files#diff-07cf3aa3a15baf93baf056bd00ebc384R53

With
https://github.com/nextcloud/android/blob/987b72846462ec889eb8259889fb8ffbbe71d601/build.gradle#L192-L196

it is only pulling one screenshot, with commenting it, it fetches both, but tests are more unreliable in general (independent from this library)
