### ISSUE TITLE
*_dump.json (No such file or directory)

### ISSUE THREAD

**Issue by patjackson52** [Karumi/Shot#66]
### Expected behaviour

Complete executeScreenshotTests task tests without FileNotFoundException

### Actual behaviour

Throws FileNotFoundException

### Steps to reproduce

Add test to project and run executeScreenshotTests 

### Version of the library

3.0.2

**Comment by pedrovgs** [comment]
Hi @patjackson52, I was wondering if you could check if you've added ``com.facebook.testing.screenshot:core`` dependency to your build and the version you are using.

Looking at the error you mention, it seems you are overriding the facebook dependency shot adds when installing the plugin. This is allowed, however, the latest library version released changed how the screenshots are saved into the device SDCard breaking the compatibility with our Shot plugin :(

If you added this library to your build.gradle, please remove it and try to execute ``./gradlew executeScreenshotTests -Precord`` again 😃

**Comment by patjackson52** [comment]
Thank you @pedrovgs .  I removed the facebook plugin (com.facebook.testing.screenshot) and the report is now generated.

**Comment by pedrovgs** [comment]
Great!
