### ISSUE TITLE
Snapshot record/verify to support large views

### ISSUE THREAD

**Issue by sahithi3390** [Karumi/Shot#68]
After upgrading from **Karumi 2.0** to **Karumi 3.0.2**, I get the following error when tried to record/verify the snapshot of screens with heightPixels >= 9000 (Which is used to take the snapshot of entire screen without having to scroll)

**java.lang.RuntimeException: java.lang.IllegalStateException: View too large: (1440, 9000)**

Function called - ViewHelpers.setupView(view)
                    .setExactHeightPx(screenHeight)
                    .setExactWidthPx(displayMetrics.widthPixels)
                    .layout()
where screenHeight = 9000 and displayMetrics.widthPixels returns 1440

**Comment by pedrovgs** [comment]
Hi @sahithi3390 I'm afraid there is nothing we can do to fix this issue. The exception you are facing is not generated by our code but the Facebook's library code. You can see the exception [here](https://github.com/facebook/screenshot-tests-for-android/blob/9d1d58e1e36414b1431fd4cd6246f3b01c816fe9/core/src/main/java/com/facebook/testing/screenshot/internal/ScreenshotImpl.java#L214)

Please, open this issue in [Facebook's library repository](https://github.com/facebook/screenshot-tests-for-android) so they can help you 😃
