### ISSUE TITLE
Trying to run with runInstrumentation = false

### ISSUE THREAD

**Issue by hernandazevedozup** [Karumi/Shot#75]
I want to verify the snapshots with files downloaded from a remote device, but I dont know where I should put the files to be compared. 

The recorded files are being saved at folder $projectdir/screenshots ( I think that those files are the current value of valid snapshots right?)
![image](https://user-images.githubusercontent.com/45759570/72186765-c20df780-33d4-11ea-84ef-eefd8f7ec953.png)

I just need to know where I should put the files downloaded from the remote device to verify with runInstrumentation = false

Can you help me?

**Comment by hernandazevedozup** [comment]
I've managed to make it work on bitrise`s Firebase Test lab using the following configuration: 
https://gist.github.com/hernandazevedo/5b2b1d68690a9a8cc3ce789c6e9f1607

**Comment by sanginovs** [comment]
@hernandazevedozup do you mind sharing how were you able to run gradle command (`./gradlew executeScreenShotTests -Precord` in Firebase test lab emulator?
