### ISSUE TITLE
Shot of dialogs

### ISSUE THREAD

**Issue by tobiasKaminsky** [Karumi/Shot#76]
### Expected behaviour
- take a snapshot of a dialog

### Actual behaviour
- dialog is omitted

### Steps to reproduce
- create a fragment like in https://developer.android.com/guide/topics/ui/dialogs
- DialogFragment dialog = DialogFragment.newInstance();
        dialog.show(getFragmentManager(), "dialogTag");
- take a screenshot with
  - Screenshot.snap(dialog.getView()).record();
  - get a NPE getMeasuredHeight()' on a null object reference
- trying to take a snapshot of activity results in a screenshot without dialog

### Version of the library
3.1.0

**Comment by pedrovgs** [comment]
Hey @tobiasKaminsky the issue you are facing is not related to the gradle pluggin we developed by the Facebook library we use under the hood. However, what if you try this:

```kotlin
Screenshot.snap(dialog.window.decorView).record()
```

Using ``dialog.window.decorView`` instead of ``dialog.getView()`` should work.

**Comment by tobiasKaminsky** [comment]
Wow. I was so sure that I have tried this.

Many many thanks for your tip and this awesome library :heart:

**Comment by tobiasKaminsky** [comment]
Maybe it is helpful for others: 
Between creation of dialog and snapshot I have to add a "Thread.sleep()".
In my case I use a delay of 2s. Maybe this is too much, but if there is no pause between, then it fails with:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Dialog.getWindow()' on a null object reference
```

**Comment by pedrovgs** [comment]
Hey @tobiasKaminsky I don't know if you test has async code or something I'm missing. Could you try using this function instead of your sleep?

```kotlin
private fun waitForAnimationsToFinish() {
        getInstrumentation().waitForIdleSync()
    }
```

If you take a look at the documentation this code will help you to synchronize your screenshot:

```
    /**
     * Synchronously wait for the application to be idle.  Can not be called
     * from the main application thread -- use {@link #start} to execute
     * instrumentation in its own thread.
     */
```

Please, check it out and let me know if this worked for you 😃

**Comment by tobiasKaminsky** [comment]
> ```kotlin
>   getInstrumentation().waitForIdleSync()
> ```

This indeed helps and is a better aproach. 
Thanks for pointing this out to me :+1:

**Comment by iadcialim** [comment]
hi. how about for permission dialogs? to how to screenshot the activity with it?

**Comment by Venkat-juju** [comment]
hi... how can i get the instance of dialog?
