### ISSUE TITLE
Support mulitple flavors in recording and comparing screenshots

### ISSUE THREAD

**Issue by tobiasKaminsky** [Karumi/Shot#77]
Currently only one flavor is possible, which is set in build.gradle.
This is an enhancement idea to support multiple flavors:
- pass option via CLI, 
  - .eg. :-Pshot.flavor=name
  - overrides setting in build.gradle
- store screenshots in /screenshots/flavor/ to support

**Comment by pedrovgs** [comment]
@tobiasKaminsky I'm afraid this is not an issue you've found but a feature request. Feel free to implement it by yourself if you need it! We are not sure if we will have time to do this. Please, rewrite your issue description too.

**Comment by tobiasKaminsky** [comment]
@pedrovgs thank you for your quick reply.
I stumbled across #16 and assumed the wrong behaviour ;-)

I updated the description. Do you think that these two steps are enough?

**Comment by pedrovgs** [comment]
I'm sorry. The name of that issue was misleading. That flavors support was related to the ability to use shot with different flavors selecting the one you want to run.

**Comment by tobiasKaminsky** [comment]
> right now when you configure shot you already pick a flavor to run in your shot configuration

I did not had a deeper look, but my goal was to have this backward compatible, so that the optional CLI parameter overrides the existing build.gradle flavor

If this does not work, I'll mention it in my (hopefully) up-to-come PR

**Comment by pedrovgs** [comment]
@tobiasKaminsky before sending any PR let's see what @Serchinastico thinks about it. Right now, when you run shot in any application with flavors you configure the flavor and the build type you want to use to run your screenshot tests. So the only thing missing is adding the flavor to the folder name. However, if we implement this feature the main benefit is will be able to use shot in different flavors at the same time by running ./gradlew executeScreenshotTests or different commands with a flavor filter as a parameter.  This will be a problem when reading the screenshots' metadata and it's not so easy to implement without the filter. What do you think @Serchinastico ?

**Comment by tobiasKaminsky** [comment]
> able to use shot in different flavors at the same time

Maybe this is a misunderstanding, but this is not what I "need" or wanted ;-)
My idea was just simply, e.g.:
- have current 20 UI tests
- have two different flavors, one is green, one is blue
- run ./gradlew execeutScreenshotTests -Pshot.flavor=green
- run ./gradlew execeutScreenshotTests -Pshot.flavor=blue

So in total there would be 40 screenshots, 20 in /screenshots/green/ and 20 in /screenshots/blue/

(background info: we can dynamically tint our app, and this might looks sometimes weird on white/black as primary color, so I want to create screenshots with these primary colors, to make sure there is no visual regression)

**Comment by Serchinastico** [comment]
The more I think about it the more I think we are talking about two different things in this issue:

1. Be able to configure the output directory for reference images.
2. To run Shot with different flavors.

Inferring the output directory from the flavor may not work for other people (if they want to compare different flavors look exactly the same).

On top of that, I'd go the standard way to include flavors in gradle tasks. That is, to register `./gradlew executeScreenshotTestsGreen` and `./gradlew executeScreenshotTestsBlue` tasks instead of using an additional parameter.

**Comment by tobiasKaminsky** [comment]
> That is, to register `./gradlew executeScreenshotTestsGreen` and `./gradlew executeScreenshotTestsBlue` tasks instead of using an additional parameter.

That is indeed the better approach! :+1: 



> Inferring the output directory from the flavor may not work for other people (if they want to compare different flavors look exactly the same).

Inferring could be the new default, and if people want to have only one output directory, they can customize it in build.gradle?

**Comment by Serchinastico** [comment]
> Inferring could be the new default, and if people want to have only one output directory, they can customize it in build.gradle?

+1 to that

**Comment by pedrovgs** [comment]
Hi @tobiasKaminsky and @Serchinastico I've been reading your comments and these are my thoughts:

* Supporting the standard build type + flavor tasks declaration is the way to go. However, we can't do this without changing where the flavors are being stored right now.
* If we enable this feature our users could potentially run the tests using ./gradlew executeScreenshotTests and this would run the tests for every flavor.
* We can't add the new task names configuration feature without implementing the folder name based on the flavor configuration.
* Before adding this feature I think we should first update the core Facebook library we use to take the screenshots. I'm creating the issue today.
* This will be a major change so we should prepare the release and plan the communication to let our users know we've changed these 3 core components: Facebook version, folder configuration based on flavor and the name of the tasks. If we don't do it properly we will end up with a lot of issues asking us why the library doesn't work. We could even release a first major version only with the Facebook's library update.

Does it makes any sense for you @Serchinastico ? Any thoughts?


@tobiasKaminsky would you like to collaborate in the flavors feature development?

**Comment by pedrovgs** [comment]
PR ready guys!! After two days of working hard, we have now the improved flavors' support we were looking for. You can take a look at the PR #95 if you want.
