### ISSUE TITLE
Support run annotated tests

### ISSUE THREAD

**Issue by PabloMGrela** [Karumi/Shot#80]
### Expected behaviour
Be able to use
./gradlew executeScreenshotTests -Pandroid.testInstrumentationRunnerArguments.annotation=com.your.package.YourAnnotation

(or default ones @LargeTest f.e.)

### Actual behaviour
If you try ro run the test suite using an annotation, it's ignored and the whole suite is run

### Steps to reproduce
-Add an annotation to a test
-Execute the command with the annotation argument

### Version of the library
3.1.0

**Comment by pedrovgs** [comment]
Hi @PabloMGrela I'll try to reproduce the error and see what's going on one day soon. Meanwhile, if someone could knows the solution just drop a comment 😃

**Comment by pedrovgs** [comment]
Hi @PabloMGrela I've just tested the usage of instrumentation runner arguments and it's working. I tried adding a ``@LargeTest`` annotation to one of my tests and using this command:

```
./gradlew executeScreenshotTests -Precord -Pandroid.testInstrumentationRunnerArguments.annotation=androidx.test.filters.LargeTest
```

And only that test was executed. I'm closing this issue for now, however if you can bring us more information about the scenario or you create a minimum reproducible project I'll try to reproduce it again. Thank you in advance 😃
