### ISSUE TITLE
Screenshot of BottomSheetDialog

### ISSUE THREAD

**Issue by tobiasKaminsky** [Karumi/Shot#81]
### Expected behaviour
create screenshot of bottomsheet dialog

### Actual behaviour
```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.facebook.testing.screenshot.internal.ScreenshotImpl.runCallableOnUiThread(ScreenshotImpl.java:335)
at com.facebook.testing.screenshot.internal.ScreenshotImpl.storeBitmap(ScreenshotImpl.java:157)
at com.facebook.testing.screenshot.internal.ScreenshotImpl.record(ScreenshotImpl.java:261)
at com.facebook.testing.screenshot.internal.RecordBuilderImpl.record(RecordBuilderImpl.java:155) 
```

### Steps to reproduce
This is a condensed code:
```
MyBottomSheetDialog dialog = new MyBottomSheetDialog();

ViewHelpers.setupView(dialog.getWindow().getDecorView())
            .setExactHeightPx(100)
            .setExactWidthPx(100)
            .layout();

Screenshot.snap(dialog.getWindow().getDecorView()).record();
```

I also tried to launch the dialog via activity and then take a snapshot. But this fails, as it only captures the acivity, but not the overlaying dialog.

A third try was:
Launching BottomSheetDialog and then:
Screenshot.snap(sut.findViewById(R.id.bottomSheetMain)).record();

but this results in:
```
java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getMeasuredHeight()' on a null object reference
```

### Version of the library
3.0.1

**Comment by pedrovgs** [comment]
@tobiasKaminsky don't you have to show the layout in any activity before taking the screenshot? Keep in mind the instrumentation tests are not executed in the app's main thread. If you create an example project reproducing the issue I can point you out how to do it. Describing the solution using plain text is not the best way to do it and I don't have any example ready with this right now.

**Comment by tobiasKaminsky** [comment]
Here you go: https://github.com/tobiasKaminsky/KarumiTest/blob/bottomSheet/app/src/androidTest/java/me/kaminsky/karumitest/BottomSheetTest.kt

Repo: git@github.com:tobiasKaminsky/KarumiTest.git
Branch: bottomSheet

Thank you :-)

**Comment by pedrovgs** [comment]
Ok @tobiasKaminsky I'm testing your project and you can't take a screenshot of a bottom sheet not attached to any activity. You'll have to take the screenshot to the activity where you are working or create an empty activity and attach it there. Anyway, this is a Facebook's library bug not something we can fix so I'm closing this issue. Feel free to ask in their repository any question you have about the usage of their library. Shot is only a gradle plugin on top of their core library 😃
