### ISSUE TITLE
Not able to contribute

### ISSUE THREAD

**Issue by vudzkostek** [Karumi/Shot#85]
I am not able to contribute into project (I could not create PR). Please checkout these changes as project has very old dependencies.

https://github.com/Karumi/Shot/compare/master...vudzkostek:update_project?expand=1

**Comment by tonilopezmr** [comment]
Hi @vudzkostek, your branch `update_project` is 81 commits behind the current `master` branch, you need to fetch the last changes from `master`.

**Comment by vudzkostek** [comment]
How is it possible if I forked project yesterday and started from master? I don't see chanhes on master from yesterday so I should be up to date. Nevertheless, I will check later and fix it, and then close issue

**Comment by vudzkostek** [comment]
@tonilopezmr my bad, I am trying to cobtribute to Kata code, not shot, but by mistake I've reported issue here

**Comment by pedrovgs** [comment]
@vudzkostek I'm checking your link and I don't get why you can not send the PR. Anyway, we are not interested in updating any dependency on the example projects, so please, do not implement these changes. I'm closing this issue.

**Comment by davideme** [comment]
@vudzkostek In the future if you want to do a PR from a fork take a look at https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork
