### ISSUE TITLE
Return useful error messages when adb process fails

### ISSUE THREAD

**Issue by SUPERCILEX** [Karumi/Shot#87]
I'm trying to debug a similar issue to https://github.com/Karumi/Shot/issues/79 and https://github.com/Karumi/Shot/issues/73 but this is next to impossible because no useful error message is return. Please pip STDERR to the console.

**Comment by pedrovgs** [comment]
@SUPERCILEX you can execute any task with this additional parameter ``--stacktrace`` if there is an exception we are not handling and you need to review more information. Thanks to this param you get all the stack trace. What else you'd like to know? These errors reported are exceptions we are not handling, not errors we want to recover from. Isn't the ``--stacktrace`` param enough for this scenario? Is there anything else you'd like to know when the build fails?

**Comment by SUPERCILEX** [comment]
`-S` only shows where the error happen. As stated above, I'd like to see the stderr from the executed command aka whatever adb logs.

**Comment by pedrovgs** [comment]
I'm afraid I don't get it @SUPERCILEX, right now there are no log traces related to errors at all. If there is something wrong we expect to handle we show the error but there are no hidden error log traces. Do you want to see the device logcat messages?

**Comment by SUPERCILEX** [comment]
There will be log traces, adb doesn't fail silently. I don't understand scala, but on this line you're crashing without piping the stderr to the console: https://github.com/Karumi/Shot/blob/6856a80cd1749aa0e4a1b9bf594fbb05d0b3b639/core/src/main/scala/com/karumi/shot/android/Adb.scala#L33 For example, in this run all we know is that the process failed with exit code 1 which isn't helpful: https://github.com/MasonAmerica/mason-check-in-kiosk/runs/473937687?check_suite_focus=true#step:8:156

I'm trying to say that somehow the logs from the adb command need to forwarded to Gradle.

**Comment by SUPERCILEX** [comment]
@pedrovgs Looks like this is what's needed: https://stackoverflow.com/a/5564667

**Comment by pedrovgs** [comment]
Ok @SUPERCILEX I get it now. I'm working on a different feature right now, however if I have time in the future I'll take a look at this issue 😃 thank you!

**Comment by SUPERCILEX** [comment]
Awesome, that would be great!

**Comment by pedrovgs** [comment]
Ready @SUPERCILEX !! This will be part of the next feature 😃

**Comment by SUPERCILEX** [comment]
Sweet!
