### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by viniciusguardieirozup** [Karumi/Shot#89]
Hi, I´m facing this error with Shot version 3.1.0 when running the command gradlew executeScreenshotTests on windows:
adb.exe: unknown command rm
![image](https://user-images.githubusercontent.com/58824112/75909767-718ea580-5e2b-11ea-9960-7218b603f922.png)

**Comment by pedrovgs** [comment]
Hi @viniciusguardieirozup I'm afraid we don't support windows for now. We are looking for contributors in order to make it work for this platform 😃

**Comment by ViniciusGuardieiroSousa** [comment]
I fix this problem on windows
