### ISSUE TITLE
Upgrade facebook dep to 0.12.0

### ISSUE THREAD

**Issue by SUPERCILEX** [Karumi/Shot#92]
The [new releases](https://github.com/facebook/screenshot-tests-for-android/releases) include support for AndroidX which would be super nice to have.

**Comment by SUPERCILEX** [comment]
Note that [`0.10.0`](https://github.com/facebook/screenshot-tests-for-android/releases/tag/0.10.0) changes how the screenshots are stored (zips them up).

**Comment by pedrovgs** [comment]
Hi @SUPERCILEX one of my latest PRs already updates the version supporting the format of the new screenshot but using the version released at that time (0.10.0) You can review it here: https://github.com/Karumi/Shot/pull/83 I'll have time to review this project in two weeks and I'll update the version then.

**Comment by SUPERCILEX** [comment]
Awesome! Any chance you make a release? Supporting AndroidX would be pretty sweet.

**Comment by SUPERCILEX** [comment]
Also, I don't care about 0.12.0 specifically, so closing.
