### ISSUE TITLE
Create tooling to be able to hide views from tests

### ISSUE THREAD

**Issue by pedrovgs** [Karumi/Shot#94]
As some of our users are facing the same problems we've faced for years we should create some tooling already integrated with the gradle plugin as a kotlin module to be able to implement the following scenarios from our tests:

* Disable the cursor for any edit text.
* Hide views by id.
* Include the test runner we always use.
* Take screenshot in a friendly and common way without even noticing the facebook library is being used.

All these scenarios should be implemented from our tests. The main goal is to avoid changing the UI behavior from our production code if we are running tests. You can use #28 as a reference of the issues faced by our users.

**Comment by pedrovgs** [comment]
After a first draft to create the core components our users are going to be able to use I'm going to continue working on the library deploy configuration and adding it automatically when the Shot gradle plugin is applied. You can find the first PR @Tylos sent here: #97

**Comment by pedrovgs** [comment]
Only the hide views by id is missing @Tylos . Would you like to implement it? Maybe @voghdev would like to implement it during the Twitch streaming. I could participate and do it together. What do you think?

**Comment by voghDev** [comment]
That'd be great!

**Comment by Tylos** [comment]
I don't have much time for the next couple of weeks so if you get the chance to work on it, do it!

**Comment by pedrovgs** [comment]
I think we are going to do it during @voghDev 's twitch streaming 😃

**Comment by fmontesino** [comment]
As an extra small idea, apart from disabling cursors and scrolls, we also manage the focus and close the soft keyboard before taking the screenshot.
In some project we "clear" the focus we iterate over all the views, starting from the root view, and then `requestFocusFromTouch()` to make it consistent. In some other projects we take a view id that will be the one that will request the focus.

Dunno if you guys will/can work on that, but if I find some time for that I could try to make a small PR if you think it'll provide value.

**Comment by pedrovgs** [comment]
Hey @fmontesino I think for a first iteration the features we've implemented are fine and we can close this issue. We've also provided support to easily add your actions before taking the screenshots by just overriding one interface method in case you need it. However, I really like your ideas and I'm wondering if you could open an issue per idea so we can implement them. If you could help ups, that'd be awesome 😃
